"""init schema

Revision ID: a25bb0e3d527
Revises: 
Create Date: 2026-09-01 03:52:21.122917+00:00

说明：
本文件由 Alembic 自动生成，请谨慎修改。
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a25bb0e3d527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构（upgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False, comment='制品 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='模型版本 ID'),
    sa.Column('revision', sa.Integer(), nullable=False, comment='版本内部制品修订号'),
    sa.Column('sha256', sa.String(length=64), nullable=True, comment='模型文件 SHA-256；历史制品可能为空'),
    sa.Column('digest', sa.String(length=64), nullable=True, comment='模型与 Schema 组合摘要；历史制品可能为空'),
    sa.Column('source_path', sa.String(length=255), nullable=False, comment='模型文件原始路径'),
    sa.Column('model_key', sa.String(length=255), nullable=False, comment='模型文件存储键'),
    sa.Column('input_schema_key', sa.String(length=255), nullable=True, comment='输入 Schema 文件存储键'),
    sa.Column('output_schema_key', sa.String(length=255), nullable=True, comment='输出 Schema 文件存储键'),
    sa.Column('bento_tag', sa.String(length=100), nullable=False, comment='BentoML 模型标签'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='制品状态'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True, comment='停止使用时间'),
    sa.Column('retired_by', sa.String(length=50), nullable=True, comment='停止使用操作人'),
    sa.Column('purge_requested_at', sa.DateTime(timezone=True), nullable=True, comment='制品清理请求时间'),
    sa.Column('purge_requested_by', sa.String(length=50), nullable=True, comment='制品清理请求人'),
    sa.Column('purge_reason', sa.TEXT(), nullable=True, comment='制品永久清理原因'),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True, comment='制品清理完成时间'),
    sa.Column('purged_by', sa.String(length=50), nullable=True, comment='制品清理完成人'),
    sa.Column('purge_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='制品清理尝试次数'),
    sa.Column('purge_error', sa.TEXT(), nullable=True, comment='最近一次制品清理错误'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('active', 'retired', 'purge_pending', 'purged', 'purge_failed')", name=op.f('ck_artifacts_status_valid')),
    sa.CheckConstraint('purge_attempts >= 0', name=op.f('ck_artifacts_purge_attempts_non_negative')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_artifacts_revision_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index('idx_artifacts_status', 'artifacts', ['status'], unique=False)
    op.create_index('idx_artifacts_version_id', 'artifacts', ['version_id'], unique=False)
    op.create_index('uk_artifacts_active_version', 'artifacts', ['version_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uk_artifacts_artifact_id', 'artifacts', ['artifact_id'], unique=True)
    op.create_index('uk_artifacts_bento_tag', 'artifacts', ['bento_tag'], unique=True)
    op.create_index('uk_artifacts_model_key', 'artifacts', ['model_key'], unique=True)
    op.create_index('uk_artifacts_version_revision', 'artifacts', ['version_id', 'revision'], unique=True)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=64), nullable=False, comment='分配 ID，实验分配记录的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=False, comment='实验分组 ID'),
    sa.Column('subject_key', sa.String(length=128), nullable=False, comment='分桶主体标识，例如客户号、订单号、申请单号'),
    sa.Column('subject_type', sa.String(length=32), nullable=True, comment='分桶主体类型，例如 customer / order / application'),
    sa.Column('strategy', sa.String(length=20), nullable=False, comment='分配策略，可选值：hash / manual'),
    sa.Column('bucket', sa.String(length=32), nullable=True, comment='分桶标识'),
    sa.Column('weight', sa.Float(), nullable=True, comment='命中分组的权重，取值范围 0.0～1.0'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='分配上下文，JSON 对象，包含实验曝光比例、分组名称和分桶过程等信息'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='主体首次固定进入实验分组的时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_assignments_context_object')),
    sa.CheckConstraint("strategy IN ('hash', 'manual')", name=op.f('ck_assignments_strategy_valid')),
    sa.CheckConstraint('weight IS NULL OR (weight >= 0 AND weight <= 1)', name=op.f('ck_assignments_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index('idx_assignments_assigned_at', 'assignments', ['assigned_at'], unique=False)
    op.create_index('idx_assignments_created_at', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignments_experiment_id', 'assignments', ['experiment_id'], unique=False)
    op.create_index('idx_assignments_subject_key', 'assignments', ['subject_key'], unique=False)
    op.create_index('idx_assignments_variant_id', 'assignments', ['variant_id'], unique=False)
    op.create_index('uk_assignments_assignment_id', 'assignments', ['assignment_id'], unique=True)
    op.create_index('uk_assignments_experiment_subject', 'assignments', ['experiment_id', 'subject_key'], unique=True)
    op.create_table('audit',
    sa.Column('audit_id', sa.String(length=64), nullable=False, comment='审计 ID，审计事件的唯一标识'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型，格式为 resource.operation，例如 model.register'),
    sa.Column('resource', sa.String(length=64), nullable=False, comment='发起当前操作的业务资源类型'),
    sa.Column('operation', sa.String(length=64), nullable=False, comment='操作名称，例如 register / create / delete / update'),
    sa.Column('target_type', sa.String(length=64), nullable=False, comment='当前操作实际作用的目标类型'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标 ID'),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'system'"), nullable=False, comment='来源类型，可选值：http / cli / system / worker / scheduler'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='触发当前审计事件的请求 ID'),
    sa.Column('user', sa.String(length=64), server_default=sa.text("'system'"), nullable=True, comment='操作者'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP 地址'),
    sa.Column('hostname', sa.String(length=128), nullable=True, comment='客户端主机名称'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'success'"), nullable=False, comment='操作状态，可选值：success / failed'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('before', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='变更前数据，JSON 格式'),
    sa.Column('after', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='变更后数据，JSON 格式'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='操作上下文，JSON 格式。可记录调用参数、操作人和扩展信息等'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='操作发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_audit_context_object')),
    sa.CheckConstraint("source IN ('http', 'cli', 'system', 'worker', 'scheduler')", name=op.f('ck_audit_source_valid')),
    sa.CheckConstraint("status IN ('success', 'failed')", name=op.f('ck_audit_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_index('idx_audit_failed_occurred_at', 'audit', ['occurred_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('idx_audit_occurred_at', 'audit', ['occurred_at'], unique=False)
    op.create_index('idx_audit_request_id_occurred_at', 'audit', ['request_id', 'occurred_at'], unique=False, postgresql_where=sa.text('request_id IS NOT NULL'))
    op.create_index('idx_audit_source_occurred_at', 'audit', ['source', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_id_occurred_at', 'audit', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_type_occurred_at', 'audit', ['target_type', 'occurred_at'], unique=False)
    op.create_index('idx_audit_trace_id_occurred_at', 'audit', ['trace_id', 'occurred_at'], unique=False, postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.create_index('idx_audit_user_occurred_at', 'audit', ['user', 'occurred_at'], unique=False)
    op.create_index('uk_audit_audit_id', 'audit', ['audit_id'], unique=True)
    op.create_table('controls',
    sa.Column('control_id', sa.String(length=64), nullable=False, comment='控制 ID，运行控制记录的唯一标识'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID，每个部署仅对应一条运行控制记录'),
    sa.Column('environment', sa.String(length=32), server_default=sa.text("'production'"), nullable=False, comment='运行环境，可选值：production / staging / development / testing'),
    sa.Column('desired_status', sa.String(length=20), server_default=sa.text("'unloaded'"), nullable=False, comment='期望运行状态，可选值：loaded / unloaded'),
    sa.Column('generation', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='控制版本号，每次状态变更或重新加载时递增'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='最近更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("desired_status IN ('loaded', 'unloaded')", name=op.f('ck_controls_desired_status_valid')),
    sa.CheckConstraint("environment IN ('production', 'staging', 'development', 'testing')", name=op.f('ck_controls_environment_valid')),
    sa.CheckConstraint('generation >= 1', name=op.f('ck_controls_generation_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controls'))
    )
    op.create_index('idx_controls_desired_status', 'controls', ['desired_status'], unique=False)
    op.create_index('idx_controls_environment', 'controls', ['environment'], unique=False)
    op.create_index('idx_controls_environment_desired_status', 'controls', ['environment', 'desired_status'], unique=False)
    op.create_index('idx_controls_updated_at', 'controls', ['updated_at'], unique=False)
    op.create_index('uk_controls_control_id', 'controls', ['control_id'], unique=True)
    op.create_index('uk_controls_deployment_id', 'controls', ['deployment_id'], unique=True)
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False, comment='决策 ID，决策记录的唯一标识'),
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='命中的模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='命中的版本 ID'),
    sa.Column('deployment_id', sa.String(length=64), nullable=True, comment='命中的部署 ID'),
    sa.Column('experiment_id', sa.String(length=64), nullable=True, comment='命中的实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=True, comment='命中的实验分组 ID'),
    sa.Column('assignment_id', sa.String(length=64), nullable=True, comment='命中的实验分配 ID'),
    sa.Column('subject_key', sa.String(length=128), nullable=True, comment='请求主体标识，例如客户号、订单号、申请单号'),
    sa.Column('subject_type', sa.String(length=32), nullable=True, comment='请求主体类型，例如 customer / order / application'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='决策来源，可选值：experiment / routing / deployment / shadow / manual'),
    sa.Column('strategy', sa.String(length=20), nullable=True, comment='路由策略，可选值：manual / hash / weighted / fallback'),
    sa.Column('bucket', sa.String(length=32), nullable=True, comment='分桶标识'),
    sa.Column('group', sa.String(length=32), nullable=True, comment='实验分组名称，例如 control / treatment'),
    sa.Column('weight', sa.Float(), nullable=True, comment='命中权重，取值范围 0.0～1.0'),
    sa.Column('decision', sa.String(length=32), nullable=True, comment='最终决策结果，例如 approve / reject / review'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='决策上下文，JSON 格式。可记录路由、实验、Worker 和运行环境等信息'),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='决策时间，请求完成模型决策的实际时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_decisions_context_object')),
    sa.CheckConstraint("source IN ('experiment', 'routing', 'deployment', 'shadow', 'manual')", name=op.f('ck_decisions_source_valid')),
    sa.CheckConstraint("strategy IS NULL OR strategy IN ('manual', 'hash', 'weighted', 'fallback')", name=op.f('ck_decisions_strategy_valid')),
    sa.CheckConstraint('weight IS NULL OR (weight >= 0 AND weight <= 1)', name=op.f('ck_decisions_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('idx_decisions_assignment_id', 'decisions', ['assignment_id'], unique=False)
    op.create_index('idx_decisions_created_at', 'decisions', ['created_at'], unique=False)
    op.create_index('idx_decisions_deployment_id', 'decisions', ['deployment_id'], unique=False)
    op.create_index('idx_decisions_experiment_id', 'decisions', ['experiment_id'], unique=False)
    op.create_index('idx_decisions_model_id', 'decisions', ['model_id'], unique=False)
    op.create_index('idx_decisions_source', 'decisions', ['source'], unique=False)
    op.create_index('idx_decisions_subject_key', 'decisions', ['subject_key'], unique=False)
    op.create_index('idx_decisions_variant_id', 'decisions', ['variant_id'], unique=False)
    op.create_index('idx_decisions_version_id', 'decisions', ['version_id'], unique=False)
    op.create_index('uk_decisions_decision_id', 'decisions', ['decision_id'], unique=True)
    op.create_index('uk_decisions_request_id', 'decisions', ['request_id'], unique=True)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID，部署实例的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'production'"), nullable=False, comment='部署环境，可选值：production / staging / development / testing'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='部署状态，可选值：active / inactive'),
    sa.Column('rollout_type', sa.String(length=20), server_default=sa.text("'full'"), nullable=False, comment='发布类型，可选值：full / canary / shadow'),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'champion'"), nullable=False, comment='部署角色，可选值：champion / challenger / shadow'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('config', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='运行时配置，JSON 对象'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='部署说明'),
    sa.Column('deployed_by', sa.String(length=50), nullable=True, comment='部署人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("(rollout_type = 'shadow' AND role = 'shadow') OR (rollout_type <> 'shadow' AND role <> 'shadow')", name=op.f('ck_deployments_shadow_role_consistent')),
    sa.CheckConstraint("config IS NULL OR jsonb_typeof(config) = 'object'", name=op.f('ck_deployments_config_object')),
    sa.CheckConstraint("environment IN ('production', 'staging', 'development', 'testing')", name=op.f('ck_deployments_environment_valid')),
    sa.CheckConstraint("role IN ('champion', 'challenger', 'shadow')", name=op.f('ck_deployments_role_valid')),
    sa.CheckConstraint("rollout_type IN ('full', 'canary', 'shadow')", name=op.f('ck_deployments_rollout_type_valid')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_deployments_status_valid')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name=op.f('ck_deployments_effective_time_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index('idx_deployments_deleted_at', 'deployments', ['deleted_at'], unique=False)
    op.create_index('idx_deployments_effective_time', 'deployments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_deployments_framework', 'deployments', ['framework'], unique=False)
    op.create_index('idx_deployments_model_id', 'deployments', ['model_id'], unique=False)
    op.create_index('idx_deployments_model_id_environment_status', 'deployments', ['model_id', 'environment', 'status'], unique=False)
    op.create_index('idx_deployments_model_id_version_id', 'deployments', ['model_id', 'version_id'], unique=False)
    op.create_index('uk_deployments_deployment_id', 'deployments', ['deployment_id'], unique=True)
    op.create_table('executions',
    sa.Column('execution_id', sa.String(length=64), nullable=False, comment='执行 ID，模型执行记录的唯一标识'),
    sa.Column('decision_id', sa.String(length=64), nullable=False, comment='关联的决策 ID，不建立数据库外键'),
    sa.Column('execution_type', sa.String(length=20), nullable=False, comment='执行类型，可选值：primary / shadow'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='执行状态，可选值：queued / running / success / failed / timeout / rejected / cancelled'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='执行使用的模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='执行使用的版本 ID'),
    sa.Column('deployment_id', sa.String(length=64), nullable=True, comment='执行使用的部署 ID，可选'),
    sa.Column('routing_id', sa.String(length=64), nullable=True, comment='命中的路由 ID'),
    sa.Column('prediction', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='模型预测结果，JSON 格式'),
    sa.Column('probability', sa.Float(), nullable=True, comment='预测概率，取值范围 0.0～1.0'),
    sa.Column('score', sa.Float(), nullable=True, comment='评分结果'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='执行耗时，单位毫秒'),
    sa.Column('error_type', sa.String(length=128), nullable=True, comment='执行失败时的错误类型'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='执行失败时的错误信息'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='模型执行上下文，JSON 格式'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='执行开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='执行结束时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("(status IN ('queued', 'running') AND finished_at IS NULL) OR (status NOT IN ('queued', 'running') AND finished_at IS NOT NULL)", name=op.f('ck_executions_unfinished_status_valid')),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_executions_context_object')),
    sa.CheckConstraint("execution_type IN ('primary', 'shadow')", name=op.f('ck_executions_execution_type_valid')),
    sa.CheckConstraint("prediction IS NULL OR jsonb_typeof(prediction) = 'object'", name=op.f('ck_executions_prediction_object')),
    sa.CheckConstraint("status IN ('queued', 'running', 'success', 'failed', 'timeout', 'rejected', 'cancelled')", name=op.f('ck_executions_status_valid')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_executions_latency_ms_non_negative')),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0 AND probability <= 1)', name=op.f('ck_executions_probability_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions'))
    )
    op.create_index('idx_executions_created_at', 'executions', ['created_at'], unique=False)
    op.create_index('idx_executions_decision_id', 'executions', ['decision_id'], unique=False)
    op.create_index('idx_executions_deployment_id', 'executions', ['deployment_id'], unique=False)
    op.create_index('idx_executions_model_id', 'executions', ['model_id'], unique=False)
    op.create_index('idx_executions_status', 'executions', ['status'], unique=False)
    op.create_index('idx_executions_type_status', 'executions', ['execution_type', 'status'], unique=False)
    op.create_index('uk_executions_decision_deployment', 'executions', ['decision_id', 'deployment_id'], unique=True)
    op.create_index('uk_executions_execution_id', 'executions', ['execution_id'], unique=True)
    op.create_index('uk_executions_primary_decision', 'executions', ['decision_id'], unique=True, postgresql_where=sa.text("execution_type = 'primary'"))
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID，实验的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'development'"), nullable=False, comment='实验环境，可选值：development / testing / staging / production'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='实验名称'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='实验描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='实验状态，可选值：draft / running / paused / stopped / completed / archived'),
    sa.Column('config', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='实验配置，JSON 对象，包含实验曝光比例、分桶字段和策略参数等信息'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_id', sa.String(length=64), nullable=True, comment='逻辑删除批次 ID'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("config IS NULL OR jsonb_typeof(config) = 'object'", name=op.f('ck_experiments_config_valid')),
    sa.CheckConstraint("environment IN ('development', 'testing', 'staging', 'production')", name=op.f('ck_experiments_environment_valid')),
    sa.CheckConstraint("status IN ('draft', 'running', 'paused', 'stopped', 'completed', 'archived')", name=op.f('ck_experiments_status_valid')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name=op.f('ck_experiments_effective_time_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('idx_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('idx_experiments_deleted_at', 'experiments', ['deleted_at'], unique=False)
    op.create_index('idx_experiments_effective_time', 'experiments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_experiments_environment', 'experiments', ['environment'], unique=False)
    op.create_index('idx_experiments_model_environment_effective_time', 'experiments', ['model_id', 'environment', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_experiments_model_environment_status', 'experiments', ['model_id', 'environment', 'status'], unique=False)
    op.create_index('idx_experiments_model_id', 'experiments', ['model_id'], unique=False)
    op.create_index('idx_experiments_model_id_status', 'experiments', ['model_id', 'status'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_index('uk_experiments_experiment_id', 'experiments', ['experiment_id'], unique=True)
    op.create_index('uk_experiments_running_model_environment', 'experiments', ['model_id', 'environment'], unique=True, postgresql_where=sa.text("status = 'running' AND deleted_at IS NULL"))
    op.create_table('grants',
    sa.Column('grant_id', sa.String(length=64), nullable=False, comment='授予 ID，角色授予记录的唯一标识'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.String(length=64), nullable=False, comment='角色 ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='授予状态，可选值：active / revoked'),
    sa.Column('granted_by', sa.String(length=64), nullable=True, comment='授予用户 ID'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='授予时间'),
    sa.Column('revoked_by', sa.String(length=64), nullable=True, comment='撤销用户 ID'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("(status = 'active' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL)", name=op.f('ck_grants_revocation_state_valid')),
    sa.CheckConstraint("btrim(role_id) <> ''", name=op.f('ck_grants_role_id_not_blank')),
    sa.CheckConstraint("btrim(user_id) <> ''", name=op.f('ck_grants_user_id_not_blank')),
    sa.CheckConstraint("granted_by IS NULL OR btrim(granted_by) <> ''", name=op.f('ck_grants_granted_by_not_blank')),
    sa.CheckConstraint("revoked_by IS NULL OR btrim(revoked_by) <> ''", name=op.f('ck_grants_revoked_by_not_blank')),
    sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f('ck_grants_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grants'))
    )
    op.create_index('idx_grants_granted_at', 'grants', ['granted_at'], unique=False)
    op.create_index('idx_grants_role_id', 'grants', ['role_id'], unique=False)
    op.create_index('idx_grants_role_status', 'grants', ['role_id', 'status'], unique=False)
    op.create_index('idx_grants_status', 'grants', ['status'], unique=False)
    op.create_index('idx_grants_user_id', 'grants', ['user_id'], unique=False)
    op.create_index('idx_grants_user_status', 'grants', ['user_id', 'status'], unique=False)
    op.create_index('uk_grants_grant_id', 'grants', ['grant_id'], unique=True)
    op.create_index('uk_grants_user_role', 'grants', ['user_id', 'role_id'], unique=True)
    op.create_table('metadata',
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID，模型的唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称，全局唯一业务标识'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='模型显示名称'),
    sa.Column('model_type', sa.String(length=50), nullable=False, comment='模型类型，可选值：logistic_regression / decision_tree / random_forest / xgboost / lightgbm / catboost'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型，可选值：classification / scoring'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='模型描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='模型状态，可选值：active / deprecated / inactive / archived'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除人'),
    sa.Column('deletion_id', sa.String(length=64), nullable=True, comment='逻辑删除 ID'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True, comment='最近恢复时间'),
    sa.Column('restored_by', sa.String(length=50), nullable=True, comment='最近恢复人'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('archived_by', sa.String(length=50), nullable=True, comment='归档人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("framework IN ('sklearn', 'xgboost', 'lightgbm', 'catboost')", name=op.f('ck_metadata_framework_valid')),
    sa.CheckConstraint("model_type IN ('logistic_regression', 'decision_tree', 'random_forest', 'xgboost', 'lightgbm', 'catboost')", name=op.f('ck_metadata_model_type_valid')),
    sa.CheckConstraint("status IN ('active', 'deprecated', 'inactive', 'archived')", name=op.f('ck_metadata_status_valid')),
    sa.CheckConstraint("task_type IN ('classification', 'scoring')", name=op.f('ck_metadata_task_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata'))
    )
    op.create_index('idx_metadata_created_at', 'metadata', ['created_at'], unique=False)
    op.create_index('idx_metadata_framework', 'metadata', ['framework'], unique=False)
    op.create_index('idx_metadata_model_type', 'metadata', ['model_type'], unique=False)
    op.create_index('idx_metadata_status', 'metadata', ['status'], unique=False)
    op.create_index('idx_metadata_task_type', 'metadata', ['task_type'], unique=False)
    op.create_index('uk_metadata_model_id', 'metadata', ['model_id'], unique=True)
    op.create_index('uk_metadata_name', 'metadata', ['name'], unique=True)
    op.create_table('outbox',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='事件游标'),
    sa.Column('topic', sa.String(length=32), nullable=False, comment='控制台数据主题'),
    sa.Column('resource_id', sa.String(length=64), nullable=True, comment='发生变化的资源 ID'),
    sa.Column('action', sa.String(length=16), nullable=False, comment='变更类型：insert / update / delete'),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='事件结构版本'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='事件发生时间'),
    sa.CheckConstraint("action IN ('insert', 'update', 'delete')", name=op.f('ck_outbox_action_valid')),
    sa.CheckConstraint("topic IN ('models', 'versions', 'deployments', 'routings', 'runtimes', 'requests', 'decisions', 'executions', 'experiments', 'variants', 'audits')", name=op.f('ck_outbox_topic_valid')),
    sa.CheckConstraint('schema_version >= 1', name=op.f('ck_outbox_schema_version_positive')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_outbox'))
    )
    op.create_index('idx_outbox_occurred_at', 'outbox', ['occurred_at'], unique=False)
    op.create_index('idx_outbox_topic_event_id', 'outbox', ['topic', 'event_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.String(length=64), nullable=False, comment='结果 ID，实验结果记录的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=True, comment='实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=True, comment='实验分组 ID'),
    sa.Column('assignment_id', sa.String(length=64), nullable=True, comment='实验分配 ID'),
    sa.Column('decision_id', sa.String(length=64), nullable=True, comment='请求决策 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID'),
    sa.Column('subject_key', sa.String(length=128), nullable=False, comment='结果主体标识，例如客户号、订单号、申请单号'),
    sa.Column('subject_type', sa.String(length=32), nullable=True, comment='结果主体类型，例如 customer / order / application'),
    sa.Column('approved', sa.Boolean(), nullable=True, comment='是否审批通过'),
    sa.Column('converted', sa.Boolean(), nullable=True, comment='是否转化，例如是否放款、是否签约、是否支用'),
    sa.Column('defaulted', sa.Boolean(), nullable=True, comment='是否违约或成为坏样本'),
    sa.Column('overdue_days', sa.Integer(), nullable=True, comment='最大逾期天数，不得小于 0'),
    sa.Column('amount', sa.Float(), nullable=True, comment='结果金额，例如审批金额、放款金额、支用金额，不得小于 0'),
    sa.Column('label', sa.String(length=32), nullable=True, comment='结果标签，例如 good / bad / unknown'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='结果上下文，JSON 格式。可记录业务结果、观测窗口和回流来源等信息'),
    sa.Column('outcome_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='结果发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_outcomes_context_object')),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_outcomes_amount_non_negative')),
    sa.CheckConstraint('overdue_days IS NULL OR overdue_days >= 0', name=op.f('ck_outcomes_overdue_days_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_index('idx_outcomes_assignment_id', 'outcomes', ['assignment_id'], unique=False)
    op.create_index('idx_outcomes_created_at', 'outcomes', ['created_at'], unique=False)
    op.create_index('idx_outcomes_decision_id', 'outcomes', ['decision_id'], unique=False)
    op.create_index('idx_outcomes_experiment_id', 'outcomes', ['experiment_id'], unique=False)
    op.create_index('idx_outcomes_outcome_time', 'outcomes', ['outcome_time'], unique=False)
    op.create_index('idx_outcomes_request_id', 'outcomes', ['request_id'], unique=False)
    op.create_index('idx_outcomes_subject_key', 'outcomes', ['subject_key'], unique=False)
    op.create_index('idx_outcomes_variant_id', 'outcomes', ['variant_id'], unique=False)
    op.create_index('uk_outcomes_outcome_id', 'outcomes', ['outcome_id'], unique=True)
    op.create_table('requests',
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID，请求的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=True, comment='目标模型 ID'),
    sa.Column('model_name', sa.String(length=255), nullable=True, comment='目标模型名称'),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='请求负载，JSON 格式。可记录模型、部署、主体和特征等请求信息'),
    sa.Column('response', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='请求处理结果，JSON 格式。记录返回给调用方的业务响应'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='请求来源，例如 api'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'received'"), nullable=False, comment='请求状态，可选值：received / success / failed'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='请求处理失败时的错误信息'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='处理耗时，单位毫秒'),
    sa.Column('user', sa.String(length=64), nullable=True, comment='用户标识'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP 地址'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("payload IS NULL OR jsonb_typeof(payload) = 'object'", name=op.f('ck_requests_payload_object')),
    sa.CheckConstraint("response IS NULL OR jsonb_typeof(response) = 'object'", name=op.f('ck_requests_response_object')),
    sa.CheckConstraint("status IN ('received', 'success', 'failed')", name=op.f('ck_requests_status_valid')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_requests_latency_ms_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_index('idx_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_requests_model_id', 'requests', ['model_id'], unique=False)
    op.create_index('idx_requests_model_name', 'requests', ['model_name'], unique=False)
    op.create_index('idx_requests_source', 'requests', ['source'], unique=False)
    op.create_index('idx_requests_status', 'requests', ['status'], unique=False)
    op.create_index('idx_requests_user', 'requests', ['user'], unique=False)
    op.create_index('uk_requests_request_id', 'requests', ['request_id'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=64), nullable=False, comment='角色 ID，角色的唯一标识'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='角色说明'),
    sa.Column('permissions', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='权限标识列表，JSON 数组。权限格式为 resource.operation'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='角色状态，可选值：active / inactive'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='更新用户 ID'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=64), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("btrim(name) <> ''", name=op.f('ck_roles_name_not_blank')),
    sa.CheckConstraint("permissions IS NULL OR jsonb_typeof(permissions) = 'array'", name=op.f('ck_roles_permissions_array')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_roles_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index('idx_roles_created_at', 'roles', ['created_at'], unique=False)
    op.create_index('idx_roles_deleted_at', 'roles', ['deleted_at'], unique=False)
    op.create_index('idx_roles_status', 'roles', ['status'], unique=False)
    op.create_index('uk_roles_name', 'roles', ['name'], unique=True)
    op.create_index('uk_roles_role_id', 'roles', ['role_id'], unique=True)
    op.create_table('routing',
    sa.Column('routing_id', sa.String(length=64), nullable=False, comment='路由 ID，路由规则的唯一标识'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='路由名称'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID'),
    sa.Column('rollout_type', sa.String(length=20), server_default=sa.text("'full'"), nullable=False, comment='发布类型，可选值：full / canary / shadow'),
    sa.Column('rollout_group', sa.String(length=64), nullable=True, comment='发布分组，可选值：champion / challenger / shadow'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'production'"), nullable=False, comment='路由环境，可选值：production / staging / development / testing'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否启用'),
    sa.Column('traffic_ratio', sa.Float(), server_default=sa.text('0'), nullable=False, comment='流量占比，取值范围 0.0～1.0'),
    sa.Column('rules', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='路由规则，JSON 格式。可记录匹配模式、条件列表和路由元信息等'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='路由说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("environment IN ('production', 'staging', 'development', 'testing')", name=op.f('ck_routing_environment_valid')),
    sa.CheckConstraint("rollout_group IS NULL OR rollout_group IN ('champion', 'challenger', 'shadow')", name=op.f('ck_routing_rollout_group_valid')),
    sa.CheckConstraint("rollout_type IN ('full', 'canary', 'shadow')", name=op.f('ck_routing_rollout_type_valid')),
    sa.CheckConstraint("rules IS NULL OR jsonb_typeof(rules) = 'object'", name=op.f('ck_routing_rules_object')),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from', name=op.f('ck_routing_effective_time_valid')),
    sa.CheckConstraint('traffic_ratio >= 0 AND traffic_ratio <= 1', name=op.f('ck_routing_traffic_ratio_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing'))
    )
    op.create_index('idx_routing_deleted_at', 'routing', ['deleted_at'], unique=False)
    op.create_index('idx_routing_environment_enabled', 'routing', ['environment', 'enabled'], unique=False)
    op.create_index('idx_routing_rollout_group_enabled', 'routing', ['rollout_group', 'enabled'], unique=False)
    op.create_index('idx_routing_rollout_type_enabled', 'routing', ['rollout_type', 'enabled'], unique=False)
    op.create_index('uk_routing_deployment_id_not_deleted', 'routing', ['deployment_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uk_routing_name_not_deleted', 'routing', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uk_routing_routing_id', 'routing', ['routing_id'], unique=True)
    op.create_table('runtimes',
    sa.Column('runtime_id', sa.String(length=64), nullable=False, comment='运行 ID，运行记录的唯一标识'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'stopped'"), nullable=False, comment='运行状态，可选值：starting / running / stopping / stopped / failed'),
    sa.Column('worker_id', sa.String(length=64), server_default=sa.text("'default'"), nullable=False, comment='运行 Worker 标识，单机模式默认 default'),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True, comment='加载时间'),
    sa.Column('unloaded_at', sa.DateTime(timezone=True), nullable=True, comment='卸载时间'),
    sa.Column('started_by', sa.String(length=50), nullable=True, comment='加载操作人'),
    sa.Column('stopped_by', sa.String(length=50), nullable=True, comment='卸载操作人'),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True, comment='最后心跳时间'),
    sa.Column('applied_generation', sa.Integer(), nullable=True, comment='控制版本号，当前 Worker 已应用的控制版本'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='运行错误信息'),
    sa.Column('context', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='运行上下文，JSON 对象，可记录模型路径、加载耗时和运行参数等信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("context IS NULL OR jsonb_typeof(context) = 'object'", name=op.f('ck_runtimes_context_object')),
    sa.CheckConstraint("framework IN ('sklearn', 'xgboost', 'lightgbm', 'catboost')", name=op.f('ck_runtimes_framework_valid')),
    sa.CheckConstraint("status IN ('starting', 'running', 'stopping', 'stopped', 'failed')", name=op.f('ck_runtimes_status_valid')),
    sa.CheckConstraint('applied_generation IS NULL OR applied_generation >= 1', name=op.f('ck_runtimes_applied_generation_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtimes'))
    )
    op.create_index('idx_runtimes_framework', 'runtimes', ['framework'], unique=False)
    op.create_index('idx_runtimes_last_heartbeat_at', 'runtimes', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_runtimes_loaded_at', 'runtimes', ['loaded_at'], unique=False)
    op.create_index('idx_runtimes_model_id', 'runtimes', ['model_id'], unique=False)
    op.create_index('idx_runtimes_status', 'runtimes', ['status'], unique=False)
    op.create_index('idx_runtimes_version_id', 'runtimes', ['version_id'], unique=False)
    op.create_index('idx_runtimes_worker_id', 'runtimes', ['worker_id'], unique=False)
    op.create_index('uk_runtimes_deployment_worker', 'runtimes', ['deployment_id', 'worker_id'], unique=True)
    op.create_index('uk_runtimes_runtime_id', 'runtimes', ['runtime_id'], unique=True)
    op.create_table('systems',
    sa.Column('system_id', sa.String(length=32), nullable=False, comment='系统标识'),
    sa.Column('initialized', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否已完成系统初始化'),
    sa.Column('initialized_at', sa.DateTime(timezone=True), nullable=True, comment='系统初始化完成时间'),
    sa.Column('initialized_by', sa.String(length=64), nullable=True, comment='系统初始化操作者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("system_id = 'datamind'", name=op.f('ck_systems_system_id_valid')),
    sa.CheckConstraint('(initialized = false AND initialized_at IS NULL AND initialized_by IS NULL) OR (initialized = true AND initialized_at IS NOT NULL AND initialized_by IS NOT NULL)', name=op.f('ck_systems_initialization_state_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_systems'))
    )
    op.create_index('uk_systems_system_id', 'systems', ['system_id'], unique=True)
    op.create_table('tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False, comment='令牌 ID，刷新令牌记录的唯一标识'),
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='刷新令牌哈希'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='令牌状态，可选值：active / revoked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='令牌过期时间'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最近使用时间'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='撤销时间'),
    sa.Column('revoked_by', sa.String(length=64), nullable=True, comment='撤销用户 ID'),
    sa.Column('revoke_reason', sa.TEXT(), nullable=True, comment='撤销原因'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='登录客户端 IP 地址'),
    sa.Column('hostname', sa.String(length=128), nullable=True, comment='登录客户端主机名称'),
    sa.Column('user_agent', sa.TEXT(), nullable=True, comment='登录客户端 User-Agent'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("(status = 'active' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL)", name=op.f('ck_tokens_revocation_state_valid')),
    sa.CheckConstraint("btrim(token_hash) <> ''", name=op.f('ck_tokens_token_hash_not_blank')),
    sa.CheckConstraint("revoked_by IS NULL OR btrim(revoked_by) <> ''", name=op.f('ck_tokens_revoked_by_not_blank')),
    sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f('ck_tokens_status_valid')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_tokens_expires_at_after_created_at')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    op.create_index('idx_tokens_expires_at', 'tokens', ['expires_at'], unique=False)
    op.create_index('idx_tokens_last_used_at', 'tokens', ['last_used_at'], unique=False)
    op.create_index('idx_tokens_status', 'tokens', ['status'], unique=False)
    op.create_index('idx_tokens_user_id', 'tokens', ['user_id'], unique=False)
    op.create_index('idx_tokens_user_status', 'tokens', ['user_id', 'status'], unique=False)
    op.create_index('uk_tokens_token_hash', 'tokens', ['token_hash'], unique=True)
    op.create_index('uk_tokens_token_id', 'tokens', ['token_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID，用户的唯一标识'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=512), nullable=False, comment='密码哈希'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='用户显示名称'),
    sa.Column('email', sa.String(length=254), nullable=True, comment='用户邮箱'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='用户状态，可选值：active / disabled / locked'),
    sa.Column('is_break_glass', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为本地应急账户'),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='临时锁定截止时间'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最近登录时间'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='最近密码修改时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='更新用户 ID'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=64), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("btrim(password_hash) <> ''", name=op.f('ck_users_password_hash_not_blank')),
    sa.CheckConstraint("btrim(username) <> ''", name=op.f('ck_users_username_not_blank')),
    sa.CheckConstraint("email IS NULL OR btrim(email) <> ''", name=op.f('ck_users_email_not_blank')),
    sa.CheckConstraint("status IN ('active', 'disabled', 'locked')", name=op.f('ck_users_status_valid')),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('uk_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uk_users_user_id', 'users', ['user_id'], unique=True)
    op.create_index('uk_users_username', 'users', ['username'], unique=True)
    op.create_table('variants',
    sa.Column('variant_id', sa.String(length=64), nullable=False, comment='实验分组 ID，实验分组的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='实验分组名称，例如 control / treatment'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='实验分组对应的部署 ID'),
    sa.Column('weight', sa.Float(), server_default=sa.text('0'), nullable=False, comment='实验内分组权重，取值范围 0.0～1.0'),
    sa.Column('is_control', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为对照组'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='实验分组状态，可选值：active / inactive / archived'),
    sa.Column('config', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='实验分组配置，JSON 对象，用于保存分组参数和策略说明'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='实验分组说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='逻辑删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='逻辑删除操作人'),
    sa.Column('deletion_id', sa.String(length=64), nullable=True, comment='逻辑删除批次 ID'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("config IS NULL OR jsonb_typeof(config) = 'object'", name=op.f('ck_variants_config_object')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'archived')", name=op.f('ck_variants_status_valid')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_variants_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_index('idx_variants_created_at', 'variants', ['created_at'], unique=False)
    op.create_index('idx_variants_deleted_at', 'variants', ['deleted_at'], unique=False)
    op.create_index('idx_variants_deployment_id', 'variants', ['deployment_id'], unique=False)
    op.create_index('idx_variants_experiment_id', 'variants', ['experiment_id'], unique=False)
    op.create_index('idx_variants_experiment_status', 'variants', ['experiment_id', 'status'], unique=False)
    op.create_index('idx_variants_status', 'variants', ['status'], unique=False)
    op.create_index('uk_variants_active_control', 'variants', ['experiment_id'], unique=True, postgresql_where=sa.text("is_control = true AND status = 'active' AND deleted_at IS NULL"))
    op.create_index('uk_variants_experiment_deployment', 'variants', ['experiment_id', 'deployment_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uk_variants_experiment_name', 'variants', ['experiment_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uk_variants_variant_id', 'variants', ['variant_id'], unique=True)
    op.create_table('versions',
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID，模型版本的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost'),
    sa.Column('input_schema', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='输入 Schema，JSON 对象'),
    sa.Column('output_schema', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='输出 Schema，JSON 对象'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='版本状态，可选值：active / inactive / deprecated / archived'),
    sa.Column('current_artifact_id', sa.String(length=64), nullable=False, comment='当前生效制品 ID'),
    sa.Column('artifact_revision', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='当前制品修订号'),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True, comment='当前模型文件 SHA-256'),
    sa.Column('artifact_digest', sa.String(length=64), nullable=True, comment='当前模型与 Schema 组合摘要'),
    sa.Column('bento_tag', sa.String(length=100), nullable=False, comment='BentoML 标签，由模型名称和 BentoML 版本组成，格式为 模型名:版本'),
    sa.Column('model_path', sa.String(length=255), nullable=False, comment='模型文件原始路径'),
    sa.Column('model_key', sa.String(length=255), nullable=False, comment='模型文件存储键'),
    sa.Column('input_schema_key', sa.String(length=255), nullable=True, comment='输入 Schema 文件存储键'),
    sa.Column('output_schema_key', sa.String(length=255), nullable=True, comment='输出 Schema 文件存储键'),
    sa.Column('params', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='模型参数，JSON 对象'),
    sa.Column('metrics', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='模型评估指标，JSON 对象'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='版本说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除人'),
    sa.Column('deletion_id', sa.String(length=64), nullable=True, comment='逻辑删除 ID'),
    sa.Column('deletion_reason', sa.TEXT(), nullable=True, comment='逻辑删除原因'),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True, comment='最近恢复时间'),
    sa.Column('restored_by', sa.String(length=50), nullable=True, comment='最近恢复人'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('archived_by', sa.String(length=50), nullable=True, comment='归档人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("framework IN ('sklearn', 'xgboost', 'lightgbm', 'catboost')", name=op.f('ck_versions_framework_valid')),
    sa.CheckConstraint("input_schema IS NULL OR jsonb_typeof(input_schema) = 'object'", name=op.f('ck_versions_input_schema_object')),
    sa.CheckConstraint("metrics IS NULL OR jsonb_typeof(metrics) = 'object'", name=op.f('ck_versions_metrics_object')),
    sa.CheckConstraint("output_schema IS NULL OR jsonb_typeof(output_schema) = 'object'", name=op.f('ck_versions_output_schema_object')),
    sa.CheckConstraint("params IS NULL OR jsonb_typeof(params) = 'object'", name=op.f('ck_versions_params_object')),
    sa.CheckConstraint("status IN ('active', 'inactive', 'deprecated', 'archived')", name=op.f('ck_versions_status_valid')),
    sa.CheckConstraint('artifact_revision >= 1', name=op.f('ck_versions_artifact_revision_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    op.create_index('idx_versions_created_at', 'versions', ['created_at'], unique=False)
    op.create_index('idx_versions_framework', 'versions', ['framework'], unique=False)
    op.create_index('idx_versions_model_id', 'versions', ['model_id'], unique=False)
    op.create_index('idx_versions_status', 'versions', ['status'], unique=False)
    op.create_index('uk_versions_model_id_version', 'versions', ['model_id', 'version'], unique=True)
    op.create_index('uk_versions_version_id', 'versions', ['version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构（downgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_versions_version_id', table_name='versions')
    op.drop_index('uk_versions_model_id_version', table_name='versions')
    op.drop_index('idx_versions_status', table_name='versions')
    op.drop_index('idx_versions_model_id', table_name='versions')
    op.drop_index('idx_versions_framework', table_name='versions')
    op.drop_index('idx_versions_created_at', table_name='versions')
    op.drop_table('versions')
    op.drop_index('uk_variants_variant_id', table_name='variants')
    op.drop_index('uk_variants_experiment_name', table_name='variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uk_variants_experiment_deployment', table_name='variants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uk_variants_active_control', table_name='variants', postgresql_where=sa.text("is_control = true AND status = 'active' AND deleted_at IS NULL"))
    op.drop_index('idx_variants_status', table_name='variants')
    op.drop_index('idx_variants_experiment_status', table_name='variants')
    op.drop_index('idx_variants_experiment_id', table_name='variants')
    op.drop_index('idx_variants_deployment_id', table_name='variants')
    op.drop_index('idx_variants_deleted_at', table_name='variants')
    op.drop_index('idx_variants_created_at', table_name='variants')
    op.drop_table('variants')
    op.drop_index('uk_users_username', table_name='users')
    op.drop_index('uk_users_user_id', table_name='users')
    op.drop_index('uk_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('uk_tokens_token_id', table_name='tokens')
    op.drop_index('uk_tokens_token_hash', table_name='tokens')
    op.drop_index('idx_tokens_user_status', table_name='tokens')
    op.drop_index('idx_tokens_user_id', table_name='tokens')
    op.drop_index('idx_tokens_status', table_name='tokens')
    op.drop_index('idx_tokens_last_used_at', table_name='tokens')
    op.drop_index('idx_tokens_expires_at', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('uk_systems_system_id', table_name='systems')
    op.drop_table('systems')
    op.drop_index('uk_runtimes_runtime_id', table_name='runtimes')
    op.drop_index('uk_runtimes_deployment_worker', table_name='runtimes')
    op.drop_index('idx_runtimes_worker_id', table_name='runtimes')
    op.drop_index('idx_runtimes_version_id', table_name='runtimes')
    op.drop_index('idx_runtimes_status', table_name='runtimes')
    op.drop_index('idx_runtimes_model_id', table_name='runtimes')
    op.drop_index('idx_runtimes_loaded_at', table_name='runtimes')
    op.drop_index('idx_runtimes_last_heartbeat_at', table_name='runtimes')
    op.drop_index('idx_runtimes_framework', table_name='runtimes')
    op.drop_table('runtimes')
    op.drop_index('uk_routing_routing_id', table_name='routing')
    op.drop_index('uk_routing_name_not_deleted', table_name='routing', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uk_routing_deployment_id_not_deleted', table_name='routing', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_routing_rollout_type_enabled', table_name='routing')
    op.drop_index('idx_routing_rollout_group_enabled', table_name='routing')
    op.drop_index('idx_routing_environment_enabled', table_name='routing')
    op.drop_index('idx_routing_deleted_at', table_name='routing')
    op.drop_table('routing')
    op.drop_index('uk_roles_role_id', table_name='roles')
    op.drop_index('uk_roles_name', table_name='roles')
    op.drop_index('idx_roles_status', table_name='roles')
    op.drop_index('idx_roles_deleted_at', table_name='roles')
    op.drop_index('idx_roles_created_at', table_name='roles')
    op.drop_table('roles')
    op.drop_index('uk_requests_request_id', table_name='requests')
    op.drop_index('idx_requests_user', table_name='requests')
    op.drop_index('idx_requests_status', table_name='requests')
    op.drop_index('idx_requests_source', table_name='requests')
    op.drop_index('idx_requests_model_name', table_name='requests')
    op.drop_index('idx_requests_model_id', table_name='requests')
    op.drop_index('idx_requests_created_at', table_name='requests')
    op.drop_table('requests')
    op.drop_index('uk_outcomes_outcome_id', table_name='outcomes')
    op.drop_index('idx_outcomes_variant_id', table_name='outcomes')
    op.drop_index('idx_outcomes_subject_key', table_name='outcomes')
    op.drop_index('idx_outcomes_request_id', table_name='outcomes')
    op.drop_index('idx_outcomes_outcome_time', table_name='outcomes')
    op.drop_index('idx_outcomes_experiment_id', table_name='outcomes')
    op.drop_index('idx_outcomes_decision_id', table_name='outcomes')
    op.drop_index('idx_outcomes_created_at', table_name='outcomes')
    op.drop_index('idx_outcomes_assignment_id', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('idx_outbox_topic_event_id', table_name='outbox')
    op.drop_index('idx_outbox_occurred_at', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('uk_metadata_name', table_name='metadata')
    op.drop_index('uk_metadata_model_id', table_name='metadata')
    op.drop_index('idx_metadata_task_type', table_name='metadata')
    op.drop_index('idx_metadata_status', table_name='metadata')
    op.drop_index('idx_metadata_model_type', table_name='metadata')
    op.drop_index('idx_metadata_framework', table_name='metadata')
    op.drop_index('idx_metadata_created_at', table_name='metadata')
    op.drop_table('metadata')
    op.drop_index('uk_grants_user_role', table_name='grants')
    op.drop_index('uk_grants_grant_id', table_name='grants')
    op.drop_index('idx_grants_user_status', table_name='grants')
    op.drop_index('idx_grants_user_id', table_name='grants')
    op.drop_index('idx_grants_status', table_name='grants')
    op.drop_index('idx_grants_role_status', table_name='grants')
    op.drop_index('idx_grants_role_id', table_name='grants')
    op.drop_index('idx_grants_granted_at', table_name='grants')
    op.drop_table('grants')
    op.drop_index('uk_experiments_running_model_environment', table_name='experiments', postgresql_where=sa.text("status = 'running' AND deleted_at IS NULL"))
    op.drop_index('uk_experiments_experiment_id', table_name='experiments')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id', table_name='experiments')
    op.drop_index('idx_experiments_model_environment_status', table_name='experiments')
    op.drop_index('idx_experiments_model_environment_effective_time', table_name='experiments')
    op.drop_index('idx_experiments_environment', table_name='experiments')
    op.drop_index('idx_experiments_effective_time', table_name='experiments')
    op.drop_index('idx_experiments_deleted_at', table_name='experiments')
    op.drop_index('idx_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('uk_executions_primary_decision', table_name='executions', postgresql_where=sa.text("execution_type = 'primary'"))
    op.drop_index('uk_executions_execution_id', table_name='executions')
    op.drop_index('uk_executions_decision_deployment', table_name='executions')
    op.drop_index('idx_executions_type_status', table_name='executions')
    op.drop_index('idx_executions_status', table_name='executions')
    op.drop_index('idx_executions_model_id', table_name='executions')
    op.drop_index('idx_executions_deployment_id', table_name='executions')
    op.drop_index('idx_executions_decision_id', table_name='executions')
    op.drop_index('idx_executions_created_at', table_name='executions')
    op.drop_table('executions')
    op.drop_index('uk_deployments_deployment_id', table_name='deployments')
    op.drop_index('idx_deployments_model_id_version_id', table_name='deployments')
    op.drop_index('idx_deployments_model_id_environment_status', table_name='deployments')
    op.drop_index('idx_deployments_model_id', table_name='deployments')
    op.drop_index('idx_deployments_framework', table_name='deployments')
    op.drop_index('idx_deployments_effective_time', table_name='deployments')
    op.drop_index('idx_deployments_deleted_at', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('uk_decisions_request_id', table_name='decisions')
    op.drop_index('uk_decisions_decision_id', table_name='decisions')
    op.drop_index('idx_decisions_version_id', table_name='decisions')
    op.drop_index('idx_decisions_variant_id', table_name='decisions')
    op.drop_index('idx_decisions_subject_key', table_name='decisions')
    op.drop_index('idx_decisions_source', table_name='decisions')
    op.drop_index('idx_decisions_model_id', table_name='decisions')
    op.drop_index('idx_decisions_experiment_id', table_name='decisions')
    op.drop_index('idx_decisions_deployment_id', table_name='decisions')
    op.drop_index('idx_decisions_created_at', table_name='decisions')
    op.drop_index('idx_decisions_assignment_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('uk_controls_deployment_id', table_name='controls')
    op.drop_index('uk_controls_control_id', table_name='controls')
    op.drop_index('idx_controls_updated_at', table_name='controls')
    op.drop_index('idx_controls_environment_desired_status', table_name='controls')
    op.drop_index('idx_controls_environment', table_name='controls')
    op.drop_index('idx_controls_desired_status', table_name='controls')
    op.drop_table('controls')
    op.drop_index('uk_audit_audit_id', table_name='audit')
    op.drop_index('idx_audit_user_occurred_at', table_name='audit')
    op.drop_index('idx_audit_trace_id_occurred_at', table_name='audit', postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.drop_index('idx_audit_target_type_occurred_at', table_name='audit')
    op.drop_index('idx_audit_target_id_occurred_at', table_name='audit')
    op.drop_index('idx_audit_source_occurred_at', table_name='audit')
    op.drop_index('idx_audit_request_id_occurred_at', table_name='audit', postgresql_where=sa.text('request_id IS NOT NULL'))
    op.drop_index('idx_audit_occurred_at', table_name='audit')
    op.drop_index('idx_audit_failed_occurred_at', table_name='audit', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('audit')
    op.drop_index('uk_assignments_experiment_subject', table_name='assignments')
    op.drop_index('uk_assignments_assignment_id', table_name='assignments')
    op.drop_index('idx_assignments_variant_id', table_name='assignments')
    op.drop_index('idx_assignments_subject_key', table_name='assignments')
    op.drop_index('idx_assignments_experiment_id', table_name='assignments')
    op.drop_index('idx_assignments_created_at', table_name='assignments')
    op.drop_index('idx_assignments_assigned_at', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('uk_artifacts_version_revision', table_name='artifacts')
    op.drop_index('uk_artifacts_model_key', table_name='artifacts')
    op.drop_index('uk_artifacts_bento_tag', table_name='artifacts')
    op.drop_index('uk_artifacts_artifact_id', table_name='artifacts')
    op.drop_index('uk_artifacts_active_version', table_name='artifacts', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_artifacts_version_id', table_name='artifacts')
    op.drop_index('idx_artifacts_status', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###