"""init schema

Revision ID: c8f331d23157
Revises: 
Create Date: 2026-07-06 12:15:29.176581+00:00

说明：
本文件由 Alembic 自动生成，请谨慎修改。
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c8f331d23157'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构（upgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=64), nullable=False, comment='分配 ID，实验分配记录的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=False, comment='实验分组 ID'),
    sa.Column('subject_key', sa.String(length=128), nullable=False, comment='分桶主体标识，例如客户号、订单号、申请单号'),
    sa.Column('subject_type', sa.String(length=32), nullable=True, comment='分桶主体类型，例如 customer / order / application'),
    sa.Column('strategy', sa.String(length=20), nullable=False, comment='分配策略，可选值：hash / manual'),
    sa.Column('bucket', sa.String(length=32), nullable=True, comment='分桶标识'),
    sa.Column('weight', sa.Float(), nullable=True, comment='命中分组的权重'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分配上下文，JSON 格式。包含实验曝光比例、分组名称、分桶过程等信息'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='分配时间，表示主体首次固定进入实验分组的时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index('idx_assignments_assigned_at', 'assignments', ['assigned_at'], unique=False)
    op.create_index('idx_assignments_created_at', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignments_experiment_id', 'assignments', ['experiment_id'], unique=False)
    op.create_index('idx_assignments_subject_key', 'assignments', ['subject_key'], unique=False)
    op.create_index('idx_assignments_variant_id', 'assignments', ['variant_id'], unique=False)
    op.create_index('uk_assignments_assignment_id', 'assignments', ['assignment_id'], unique=True)
    op.create_index('uk_assignments_experiment_subject', 'assignments', ['experiment_id', 'subject_key'], unique=True)
    op.create_table('audit',
    sa.Column('audit_id', sa.String(length=64), nullable=False, comment='审计 ID，审计事件的唯一标识'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型，格式为 resource.operation，如 model.register'),
    sa.Column('resource', sa.String(length=64), nullable=False, comment='资源类型，表示发起当前操作的业务模块，可选值：model / version / deployment / experiment'),
    sa.Column('operation', sa.String(length=64), nullable=False, comment='操作名称，如 register / create / delete / update'),
    sa.Column('target_type', sa.String(length=64), nullable=False, comment='目标类型，表示当前操作实际作用的业务对象类型，可选值：model / version / deployment / experiment'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标 ID'),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'system'"), nullable=False, comment='来源类型，可选值：http / cli / system / worker / scheduler'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID，用于关联触发当前审计事件的请求'),
    sa.Column('user', sa.String(length=64), server_default='system', nullable=True, comment='操作者'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP 地址'),
    sa.Column('hostname', sa.String(length=128), nullable=True, comment='客户端主机名称'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'success'"), nullable=False, comment='操作状态，可选值：success / failed'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更前数据，JSON 格式'),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更后数据，JSON 格式'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作上下文，JSON 格式'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='操作发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_index('idx_audit_failed_occurred_at', 'audit', ['occurred_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('idx_audit_occurred_at', 'audit', ['occurred_at'], unique=False)
    op.create_index('idx_audit_request_id_occurred_at', 'audit', ['request_id', 'occurred_at'], unique=False, postgresql_where=sa.text('request_id IS NOT NULL'))
    op.create_index('idx_audit_source_occurred_at', 'audit', ['source', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_id_occurred_at', 'audit', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_type_occurred_at', 'audit', ['target_type', 'occurred_at'], unique=False)
    op.create_index('idx_audit_trace_id_occurred_at', 'audit', ['trace_id', 'occurred_at'], unique=False, postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.create_index('idx_audit_user_occurred_at', 'audit', ['user', 'occurred_at'], unique=False)
    op.create_index('uk_audit_audit_id', 'audit', ['audit_id'], unique=True)
    op.create_table('controls',
    sa.Column('control_id', sa.String(length=64), nullable=False, comment='控制 ID，运行控制记录的唯一标识'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID，每个部署仅对应一条运行控制记录'),
    sa.Column('desired_status', sa.String(length=20), server_default=sa.text("'unloaded'"), nullable=False, comment='期望运行状态，可选值：loaded / unloaded'),
    sa.Column('generation', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='控制版本号，每次状态变更或重新加载时递增'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='最近更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('generation >= 1', name=op.f('ck_controls_generation_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controls'))
    )
    op.create_index('idx_controls_deployment_id', 'controls', ['deployment_id'], unique=False)
    op.create_index('idx_controls_desired_status', 'controls', ['desired_status'], unique=False)
    op.create_index('idx_controls_updated_at', 'controls', ['updated_at'], unique=False)
    op.create_index('uk_controls_control_id', 'controls', ['control_id'], unique=True)
    op.create_index('uk_controls_deployment_id', 'controls', ['deployment_id'], unique=True)
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False, comment='决策 ID，决策记录的唯一标识'),
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='命中的模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='命中的版本 ID'),
    sa.Column('deployment_id', sa.String(length=64), nullable=True, comment='命中的部署 ID'),
    sa.Column('experiment_id', sa.String(length=64), nullable=True, comment='命中的实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=True, comment='命中的实验分组 ID'),
    sa.Column('customer_id', sa.String(length=64), nullable=False, comment='请求主体标识'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='决策来源，可选值：experiment / routing / deployment / shadow / manual'),
    sa.Column('strategy', sa.String(length=20), nullable=True, comment='流量分配策略，可选值：random / hash / bucket / weighted'),
    sa.Column('bucket', sa.String(length=32), nullable=True, comment='分桶标识'),
    sa.Column('group', sa.String(length=32), nullable=True, comment='实验分组名称，如 control / treatment'),
    sa.Column('weight', sa.Float(), nullable=True, comment='命中分组的权重'),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型预测结果，JSON 格式'),
    sa.Column('probability', sa.Float(), nullable=True, comment='预测概率'),
    sa.Column('score', sa.Float(), nullable=True, comment='评分结果'),
    sa.Column('decision', sa.String(length=32), nullable=True, comment='最终决策结果，如 approve / reject / review'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='决策耗时，单位毫秒'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='决策上下文，JSON 格式。包含路由、实验、模型输出等调试信息'),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='决策时间，表示请求完成模型决策的实际时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('idx_decisions_created_at', 'decisions', ['created_at'], unique=False)
    op.create_index('idx_decisions_customer_id', 'decisions', ['customer_id'], unique=False)
    op.create_index('idx_decisions_deployment_id', 'decisions', ['deployment_id'], unique=False)
    op.create_index('idx_decisions_experiment_id', 'decisions', ['experiment_id'], unique=False)
    op.create_index('idx_decisions_model_id', 'decisions', ['model_id'], unique=False)
    op.create_index('idx_decisions_source', 'decisions', ['source'], unique=False)
    op.create_index('idx_decisions_variant_id', 'decisions', ['variant_id'], unique=False)
    op.create_index('idx_decisions_version_id', 'decisions', ['version_id'], unique=False)
    op.create_index('uk_decisions_decision_id', 'decisions', ['decision_id'], unique=True)
    op.create_index('uk_decisions_request_id', 'decisions', ['request_id'], unique=True)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID，部署实例的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，表示当前部署实例运行的模型框架，可选值 sklearn / xgboost / lightgbm / catboost'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'production'"), nullable=False, comment='部署环境，可选值：production / staging / development / testing'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='部署状态，可选值：active / inactive'),
    sa.Column('rollout_type', sa.String(length=20), server_default=sa.text("'full'"), nullable=False, comment='发布类型，仅用于标识发布方式，可选值：full / canary / shadow'),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'champion'"), nullable=False, comment='部署角色：champion / challenger / shadow'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='运行时配置，JSON 格式'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='部署说明'),
    sa.Column('deployed_by', sa.String(length=50), nullable=True, comment='部署人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index('idx_deployments_effective_time', 'deployments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_deployments_framework', 'deployments', ['framework'], unique=False)
    op.create_index('idx_deployments_model_id', 'deployments', ['model_id'], unique=False)
    op.create_index('idx_deployments_model_id_environment_status', 'deployments', ['model_id', 'environment', 'status'], unique=False)
    op.create_index('idx_deployments_model_id_version_id', 'deployments', ['model_id', 'version_id'], unique=False)
    op.create_index('uk_deployments_deployment_id', 'deployments', ['deployment_id'], unique=True)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID，实验的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='实验名称'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='实验描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='实验状态，可选值：draft / running / paused / stopped / completed / archived'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='实验配置，JSON 格式。包含实验曝光比例、分桶字段、策略参数等信息'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('idx_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('idx_experiments_effective_time', 'experiments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_experiments_model_id', 'experiments', ['model_id'], unique=False)
    op.create_index('idx_experiments_model_id_status', 'experiments', ['model_id', 'status'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_index('uk_experiments_experiment_id', 'experiments', ['experiment_id'], unique=True)
    op.create_table('metadata',
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID，模型的唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称，全局唯一业务标识'),
    sa.Column('model_type', sa.String(length=50), nullable=False, comment='模型类型，可选值：logistic_regression / decision_tree / random_forest / xgboost / lightgbm / catboost'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型，可选值：classification / scoring'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='模型描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='状态，可选值：active / deprecated / inactive / archived'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除人'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('archived_by', sa.String(length=50), nullable=True, comment='归档人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata'))
    )
    op.create_index('idx_metadata_created_at', 'metadata', ['created_at'], unique=False)
    op.create_index('idx_metadata_framework', 'metadata', ['framework'], unique=False)
    op.create_index('idx_metadata_model_type', 'metadata', ['model_type'], unique=False)
    op.create_index('idx_metadata_status', 'metadata', ['status'], unique=False)
    op.create_index('idx_metadata_task_type', 'metadata', ['task_type'], unique=False)
    op.create_index('uk_metadata_model_id', 'metadata', ['model_id'], unique=True)
    op.create_index('uk_metadata_name', 'metadata', ['name'], unique=True)
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.String(length=64), nullable=False, comment='结果 ID，实验结果记录的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=True, comment='实验 ID'),
    sa.Column('variant_id', sa.String(length=64), nullable=True, comment='实验分组 ID'),
    sa.Column('assignment_id', sa.String(length=64), nullable=True, comment='实验分配 ID'),
    sa.Column('decision_id', sa.String(length=64), nullable=True, comment='请求决策 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID'),
    sa.Column('subject_key', sa.String(length=128), nullable=False, comment='结果主体标识，例如客户号、订单号、申请单号'),
    sa.Column('subject_type', sa.String(length=32), nullable=True, comment='结果主体类型，例如 customer / order / application'),
    sa.Column('approved', sa.Boolean(), nullable=True, comment='是否审批通过'),
    sa.Column('converted', sa.Boolean(), nullable=True, comment='是否转化，例如是否放款、是否签约、是否支用'),
    sa.Column('defaulted', sa.Boolean(), nullable=True, comment='是否违约或成为坏样本'),
    sa.Column('overdue_days', sa.Integer(), nullable=True, comment='最大逾期天数'),
    sa.Column('amount', sa.Float(), nullable=True, comment='结果金额，例如审批金额、放款金额、支用金额'),
    sa.Column('label', sa.String(length=32), nullable=True, comment='结果标签，例如 good / bad / unknown'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='结果上下文，JSON 格式。包含业务结果、观测窗口、回流来源等信息'),
    sa.Column('outcome_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='结果发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_index('idx_outcomes_assignment_id', 'outcomes', ['assignment_id'], unique=False)
    op.create_index('idx_outcomes_created_at', 'outcomes', ['created_at'], unique=False)
    op.create_index('idx_outcomes_decision_id', 'outcomes', ['decision_id'], unique=False)
    op.create_index('idx_outcomes_experiment_id', 'outcomes', ['experiment_id'], unique=False)
    op.create_index('idx_outcomes_outcome_time', 'outcomes', ['outcome_time'], unique=False)
    op.create_index('idx_outcomes_request_id', 'outcomes', ['request_id'], unique=False)
    op.create_index('idx_outcomes_subject_key', 'outcomes', ['subject_key'], unique=False)
    op.create_index('idx_outcomes_variant_id', 'outcomes', ['variant_id'], unique=False)
    op.create_index('uk_outcomes_outcome_id', 'outcomes', ['outcome_id'], unique=True)
    op.create_table('requests',
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID，请求的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='目标模型 ID'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求负载，JSON 格式'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='请求来源，如 api'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='处理耗时，单位毫秒'),
    sa.Column('user', sa.String(length=64), nullable=True, comment='用户标识'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP 地址'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_requests_request_id'))
    )
    op.create_index('idx_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_requests_model_id', 'requests', ['model_id'], unique=False)
    op.create_index('idx_requests_request_id', 'requests', ['request_id'], unique=False)
    op.create_index('idx_requests_source', 'requests', ['source'], unique=False)
    op.create_index('idx_requests_user', 'requests', ['user'], unique=False)
    op.create_table('routing',
    sa.Column('routing_id', sa.String(length=64), nullable=False, comment='路由 ID，路由的唯一标志'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID'),
    sa.Column('rollout_type', sa.String(length=20), server_default=sa.text("'full'"), nullable=False, comment='发布类型，仅用于标识发布方式，可选值：full / canary / shadow'),
    sa.Column('rollout_group', sa.String(length=64), nullable=True, comment='发布分组'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'production'"), nullable=False, comment='路由环境'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('traffic_ratio', sa.Float(), server_default=sa.text('0'), nullable=False, comment='流量占比，取值范围 0.0 ~ 1.0'),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='路由规则配置，JSON 格式'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='路由说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('traffic_ratio >= 0 AND traffic_ratio <= 1', name=op.f('ck_routing_ck_traffic_ratio_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing'))
    )
    op.create_index('idx_routing_deployment_id', 'routing', ['deployment_id'], unique=False)
    op.create_index('idx_routing_environment_enabled', 'routing', ['environment', 'enabled'], unique=False)
    op.create_index('idx_routing_rollout_group_enabled', 'routing', ['rollout_group', 'enabled'], unique=False)
    op.create_index('idx_routing_rollout_type_enabled', 'routing', ['rollout_type', 'enabled'], unique=False)
    op.create_index('uk_routing_routing_id', 'routing', ['routing_id'], unique=True)
    op.create_table('runtimes',
    sa.Column('runtime_id', sa.String(length=64), nullable=False, comment='运行 ID，运行记录的唯一标识'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值 sklearn / xgboost / lightgbm / catboost'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'unloaded'"), nullable=False, comment='运行状态，可选值：loading / loaded / unloaded / failed'),
    sa.Column('worker_id', sa.String(length=64), server_default=sa.text("'default'"), nullable=False, comment='运行 Worker 标识，单机模式默认 default'),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True, comment='加载时间'),
    sa.Column('unloaded_at', sa.DateTime(timezone=True), nullable=True, comment='卸载时间'),
    sa.Column('started_by', sa.String(length=50), nullable=True, comment='加载操作人'),
    sa.Column('stopped_by', sa.String(length=50), nullable=True, comment='卸载操作人'),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True, comment='最后心跳时间'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='运行错误信息'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='运行上下文，JSON 格式。可记录模型路径、加载耗时、运行参数等信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtimes'))
    )
    op.create_index('idx_runtimes_deployment_id', 'runtimes', ['deployment_id'], unique=False)
    op.create_index('idx_runtimes_framework', 'runtimes', ['framework'], unique=False)
    op.create_index('idx_runtimes_last_heartbeat_at', 'runtimes', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_runtimes_loaded_at', 'runtimes', ['loaded_at'], unique=False)
    op.create_index('idx_runtimes_model_id', 'runtimes', ['model_id'], unique=False)
    op.create_index('idx_runtimes_status', 'runtimes', ['status'], unique=False)
    op.create_index('idx_runtimes_version_id', 'runtimes', ['version_id'], unique=False)
    op.create_index('idx_runtimes_worker_id', 'runtimes', ['worker_id'], unique=False)
    op.create_index('uk_runtimes_deployment_worker', 'runtimes', ['deployment_id', 'worker_id'], unique=True)
    op.create_index('uk_runtimes_runtime_id', 'runtimes', ['runtime_id'], unique=True)
    op.create_table('variants',
    sa.Column('variant_id', sa.String(length=64), nullable=False, comment='实验分组 ID，实验分组的唯一标识'),
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='实验分组名称，例如 control / treatment / challenger'),
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='实验分组对应的部署 ID'),
    sa.Column('weight', sa.Float(), server_default=sa.text('0'), nullable=False, comment='实验内分组权重，取值范围 0.0 ~ 1.0'),
    sa.Column('is_control', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为对照组'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='实验分组状态，可选值：active / inactive / archived'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='实验分组配置，JSON 格式。可保存分组参数、策略说明等信息'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='实验分组说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_variants_ck_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_index('idx_variants_created_at', 'variants', ['created_at'], unique=False)
    op.create_index('idx_variants_deployment_id', 'variants', ['deployment_id'], unique=False)
    op.create_index('idx_variants_experiment_id', 'variants', ['experiment_id'], unique=False)
    op.create_index('idx_variants_experiment_status', 'variants', ['experiment_id', 'status'], unique=False)
    op.create_index('idx_variants_status', 'variants', ['status'], unique=False)
    op.create_index('uk_variants_experiment_name', 'variants', ['experiment_id', 'name'], unique=True)
    op.create_index('uk_variants_variant_id', 'variants', ['variant_id'], unique=True)
    op.create_table('versions',
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID，模型版本的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，如 sklearn / xgboost / lightgbm / catboost'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输入 Schema，JSON 格式'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输出 Schema，JSON 格式'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='状态，可选值：active / inactive / deprecated / archived'),
    sa.Column('bento_tag', sa.String(length=100), nullable=False, comment='BentoML 标签，格式为 模型名:版本'),
    sa.Column('model_path', sa.String(length=255), nullable=False, comment='模型文件存储路径'),
    sa.Column('model_key', sa.String(length=255), nullable=False, comment='模型文件存储键'),
    sa.Column('input_schema_key', sa.String(length=255), nullable=True, comment='输入 Schema 文件存储键'),
    sa.Column('output_schema_key', sa.String(length=255), nullable=True, comment='输出 Schema 文件存储键'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型参数，JSON 格式'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型评估指标，JSON 格式'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='版本说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除人'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('archived_by', sa.String(length=50), nullable=True, comment='归档人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    op.create_index('idx_versions_created_at', 'versions', ['created_at'], unique=False)
    op.create_index('idx_versions_framework', 'versions', ['framework'], unique=False)
    op.create_index('idx_versions_model_id', 'versions', ['model_id'], unique=False)
    op.create_index('idx_versions_status', 'versions', ['status'], unique=False)
    op.create_index('uk_versions_model_id_version', 'versions', ['model_id', 'version'], unique=True)
    op.create_index('uk_versions_version_id', 'versions', ['version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构（downgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_versions_version_id', table_name='versions')
    op.drop_index('uk_versions_model_id_version', table_name='versions')
    op.drop_index('idx_versions_status', table_name='versions')
    op.drop_index('idx_versions_model_id', table_name='versions')
    op.drop_index('idx_versions_framework', table_name='versions')
    op.drop_index('idx_versions_created_at', table_name='versions')
    op.drop_table('versions')
    op.drop_index('uk_variants_variant_id', table_name='variants')
    op.drop_index('uk_variants_experiment_name', table_name='variants')
    op.drop_index('idx_variants_status', table_name='variants')
    op.drop_index('idx_variants_experiment_status', table_name='variants')
    op.drop_index('idx_variants_experiment_id', table_name='variants')
    op.drop_index('idx_variants_deployment_id', table_name='variants')
    op.drop_index('idx_variants_created_at', table_name='variants')
    op.drop_table('variants')
    op.drop_index('uk_runtimes_runtime_id', table_name='runtimes')
    op.drop_index('uk_runtimes_deployment_worker', table_name='runtimes')
    op.drop_index('idx_runtimes_worker_id', table_name='runtimes')
    op.drop_index('idx_runtimes_version_id', table_name='runtimes')
    op.drop_index('idx_runtimes_status', table_name='runtimes')
    op.drop_index('idx_runtimes_model_id', table_name='runtimes')
    op.drop_index('idx_runtimes_loaded_at', table_name='runtimes')
    op.drop_index('idx_runtimes_last_heartbeat_at', table_name='runtimes')
    op.drop_index('idx_runtimes_framework', table_name='runtimes')
    op.drop_index('idx_runtimes_deployment_id', table_name='runtimes')
    op.drop_table('runtimes')
    op.drop_index('uk_routing_routing_id', table_name='routing')
    op.drop_index('idx_routing_rollout_type_enabled', table_name='routing')
    op.drop_index('idx_routing_rollout_group_enabled', table_name='routing')
    op.drop_index('idx_routing_environment_enabled', table_name='routing')
    op.drop_index('idx_routing_deployment_id', table_name='routing')
    op.drop_table('routing')
    op.drop_index('idx_requests_user', table_name='requests')
    op.drop_index('idx_requests_source', table_name='requests')
    op.drop_index('idx_requests_request_id', table_name='requests')
    op.drop_index('idx_requests_model_id', table_name='requests')
    op.drop_index('idx_requests_created_at', table_name='requests')
    op.drop_table('requests')
    op.drop_index('uk_outcomes_outcome_id', table_name='outcomes')
    op.drop_index('idx_outcomes_variant_id', table_name='outcomes')
    op.drop_index('idx_outcomes_subject_key', table_name='outcomes')
    op.drop_index('idx_outcomes_request_id', table_name='outcomes')
    op.drop_index('idx_outcomes_outcome_time', table_name='outcomes')
    op.drop_index('idx_outcomes_experiment_id', table_name='outcomes')
    op.drop_index('idx_outcomes_decision_id', table_name='outcomes')
    op.drop_index('idx_outcomes_created_at', table_name='outcomes')
    op.drop_index('idx_outcomes_assignment_id', table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index('uk_metadata_name', table_name='metadata')
    op.drop_index('uk_metadata_model_id', table_name='metadata')
    op.drop_index('idx_metadata_task_type', table_name='metadata')
    op.drop_index('idx_metadata_status', table_name='metadata')
    op.drop_index('idx_metadata_model_type', table_name='metadata')
    op.drop_index('idx_metadata_framework', table_name='metadata')
    op.drop_index('idx_metadata_created_at', table_name='metadata')
    op.drop_table('metadata')
    op.drop_index('uk_experiments_experiment_id', table_name='experiments')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id', table_name='experiments')
    op.drop_index('idx_experiments_effective_time', table_name='experiments')
    op.drop_index('idx_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('uk_deployments_deployment_id', table_name='deployments')
    op.drop_index('idx_deployments_model_id_version_id', table_name='deployments')
    op.drop_index('idx_deployments_model_id_environment_status', table_name='deployments')
    op.drop_index('idx_deployments_model_id', table_name='deployments')
    op.drop_index('idx_deployments_framework', table_name='deployments')
    op.drop_index('idx_deployments_effective_time', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('uk_decisions_request_id', table_name='decisions')
    op.drop_index('uk_decisions_decision_id', table_name='decisions')
    op.drop_index('idx_decisions_version_id', table_name='decisions')
    op.drop_index('idx_decisions_variant_id', table_name='decisions')
    op.drop_index('idx_decisions_source', table_name='decisions')
    op.drop_index('idx_decisions_model_id', table_name='decisions')
    op.drop_index('idx_decisions_experiment_id', table_name='decisions')
    op.drop_index('idx_decisions_deployment_id', table_name='decisions')
    op.drop_index('idx_decisions_customer_id', table_name='decisions')
    op.drop_index('idx_decisions_created_at', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('uk_controls_deployment_id', table_name='controls')
    op.drop_index('uk_controls_control_id', table_name='controls')
    op.drop_index('idx_controls_updated_at', table_name='controls')
    op.drop_index('idx_controls_desired_status', table_name='controls')
    op.drop_index('idx_controls_deployment_id', table_name='controls')
    op.drop_table('controls')
    op.drop_index('uk_audit_audit_id', table_name='audit')
    op.drop_index('idx_audit_user_occurred_at', table_name='audit')
    op.drop_index('idx_audit_trace_id_occurred_at', table_name='audit', postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.drop_index('idx_audit_target_type_occurred_at', table_name='audit')
    op.drop_index('idx_audit_target_id_occurred_at', table_name='audit')
    op.drop_index('idx_audit_source_occurred_at', table_name='audit')
    op.drop_index('idx_audit_request_id_occurred_at', table_name='audit', postgresql_where=sa.text('request_id IS NOT NULL'))
    op.drop_index('idx_audit_occurred_at', table_name='audit')
    op.drop_index('idx_audit_failed_occurred_at', table_name='audit', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('audit')
    op.drop_index('uk_assignments_experiment_subject', table_name='assignments')
    op.drop_index('uk_assignments_assignment_id', table_name='assignments')
    op.drop_index('idx_assignments_variant_id', table_name='assignments')
    op.drop_index('idx_assignments_subject_key', table_name='assignments')
    op.drop_index('idx_assignments_experiment_id', table_name='assignments')
    op.drop_index('idx_assignments_created_at', table_name='assignments')
    op.drop_index('idx_assignments_assigned_at', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###