"""init schema

Revision ID: c0fac46cf547
Revises: 
Create Date: 2026-05-15 07:20:15.601332+00:00

说明：
本文件由 Alembic 自动生成，请谨慎修改。
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c0fac46cf547'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构（upgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=64), nullable=False, comment='分配 ID，分配的唯一标识'),
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='被分配到的模型 ID'),
    sa.Column('version_id', sa.String(length=50), nullable=False, comment='被分配的版本 ID'),
    sa.Column('deployment_id', sa.String(length=64), nullable=True, comment='命中的部署 ID'),
    sa.Column('experiment_id', sa.String(length=64), nullable=True, comment='命中的实验 ID'),
    sa.Column('customer_id', sa.String(length=64), nullable=False, comment='请求主体标识'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='路由来源，可选值：experiment / deployment / routing'),
    sa.Column('strategy', sa.String(length=20), nullable=True, comment='流量分配策略，可选值：random / consistent / bucket / weighted'),
    sa.Column('bucket', sa.String(length=32), nullable=True, comment='分桶标识'),
    sa.Column('group', sa.String(length=32), nullable=True, comment='实验分组，如 control / treatment'),
    sa.Column('weight', sa.Float(), nullable=True, comment='分配权重，表示当前请求在该实验分组中的概率权重'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分配上下文，JSON 格式。包含所有分配过程的信息，仅用于跟踪和调试'),
    sa.Column('routed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='路由分配时间，表示请求被分配到目标模型版本的实际时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index('idx_assignments_created_at', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignments_customer_id', 'assignments', ['customer_id'], unique=False)
    op.create_index('idx_assignments_deployment_id', 'assignments', ['deployment_id'], unique=False)
    op.create_index('idx_assignments_experiment_id', 'assignments', ['experiment_id'], unique=False)
    op.create_index('idx_assignments_model_id', 'assignments', ['model_id'], unique=False)
    op.create_index('idx_assignments_source', 'assignments', ['source'], unique=False)
    op.create_index('idx_assignments_version_id', 'assignments', ['version_id'], unique=False)
    op.create_index('uk_assignments_assignment_id', 'assignments', ['assignment_id'], unique=True)
    op.create_index('uk_assignments_request_id', 'assignments', ['request_id'], unique=True)
    op.create_table('audit',
    sa.Column('audit_id', sa.String(length=64), nullable=False, comment='审计 ID，审计事件的唯一标识'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型，格式为 resource.operation，如 model.register'),
    sa.Column('resource', sa.String(length=64), nullable=False, comment='资源类型，表示发起当前操作的业务模块，可选值：model / version / deployment / experiment'),
    sa.Column('operation', sa.String(length=64), nullable=False, comment='操作名称，如 register / create / delete / update'),
    sa.Column('target_type', sa.String(length=64), nullable=False, comment='目标类型，表示当前操作实际作用的业务对象类型，可选值：model / version / deployment / experiment'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标 ID'),
    sa.Column('source', sa.String(length=16), server_default=sa.text("'system'"), nullable=False, comment='来源类型，可选值：http / cli / system / worker / scheduler'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求 ID，用于关联触发当前审计事件的请求'),
    sa.Column('user', sa.String(length=64), server_default='system', nullable=True, comment='操作者'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='操作者 IP'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'success'"), nullable=False, comment='操作状态，可选值：success / failed'),
    sa.Column('error', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更前数据，JSON 格式'),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更后数据，JSON 格式'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作上下文，JSON 格式'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='操作发生时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_index('idx_audit_failed_occurred_at', 'audit', ['occurred_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('idx_audit_occurred_at', 'audit', ['occurred_at'], unique=False)
    op.create_index('idx_audit_request_id_occurred_at', 'audit', ['request_id', 'occurred_at'], unique=False, postgresql_where=sa.text('request_id IS NOT NULL'))
    op.create_index('idx_audit_source_occurred_at', 'audit', ['source', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_id_occurred_at', 'audit', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_type_occurred_at', 'audit', ['target_type', 'occurred_at'], unique=False)
    op.create_index('idx_audit_trace_id_occurred_at', 'audit', ['trace_id', 'occurred_at'], unique=False, postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.create_index('idx_audit_user_occurred_at', 'audit', ['user', 'occurred_at'], unique=False)
    op.create_index('uk_audit_audit_id', 'audit', ['audit_id'], unique=True)
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=64), nullable=False, comment='部署 ID，部署实例的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，表示当前部署实例运行的模型框架，可选值 sklearn / xgboost / lightgbm / catboost / torch / onnx / tensorflow'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='部署状态，可选值：active / inactive'),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'production'"), nullable=False, comment='部署环境，可选值：production / staging / development / testing'),
    sa.Column('rollout_type', sa.String(length=20), server_default=sa.text("'full'"), nullable=False, comment='发布类型，仅用于标识发布方式，可选值：full / canary / shadow'),
    sa.Column('variant', sa.String(length=20), server_default=sa.text("'primary'"), nullable=False, comment='部署角色：primary / canary'),
    sa.Column('traffic_ratio', sa.Float(), server_default=sa.text('1.0'), nullable=False, comment='流量占比，取值范围 0.0 ~ 1.0'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('deployed_by', sa.String(length=50), nullable=True, comment='部署人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('description', sa.Text(), nullable=True, comment='部署说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('traffic_ratio >= 0 AND traffic_ratio <= 1', name=op.f('ck_deployments_ck_traffic_ratio_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index('idx_deployments_effective_time', 'deployments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_deployments_environment_variant_status', 'deployments', ['environment', 'variant', 'status'], unique=False)
    op.create_index('idx_deployments_framework', 'deployments', ['framework'], unique=False)
    op.create_index('idx_deployments_model_id', 'deployments', ['model_id'], unique=False)
    op.create_index('idx_deployments_model_version', 'deployments', ['model_id', 'version_id'], unique=False)
    op.create_index('uk_deployments_deployment_id', 'deployments', ['deployment_id'], unique=True)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=64), nullable=False, comment='实验 ID，实验的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='实验名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='实验描述'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False, comment='实验状态，可选值：draft / running / paused / stopped / completed'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='实验配置，JSON 格式。包含流量分配策略、实验变体及权重配置等，仅用于跟踪和调试'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('idx_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('idx_experiments_effective_time', 'experiments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_experiments_model_id', 'experiments', ['model_id'], unique=False)
    op.create_index('idx_experiments_model_id_status', 'experiments', ['model_id', 'status'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_index('uk_experiments_experiment_id', 'experiments', ['experiment_id'], unique=True)
    op.create_table('metadata',
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID，模型的唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称，全局唯一业务标识'),
    sa.Column('model_type', sa.String(length=50), nullable=False, comment='模型类型，可选值：logistic_regression / decision_tree / random_forest / xgboost / lightgbm / catboost'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型，可选值：classification / scoring'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，可选值：sklearn / xgboost / lightgbm / catboost / torch / onnx / tensorflow'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='模型描述'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输入 Schema，JSON 格式'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输出 Schema，JSON 格式'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='状态，可选值：active / inactive / deprecated / archived'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata'))
    )
    op.create_index('idx_metadata_created_at', 'metadata', ['created_at'], unique=False)
    op.create_index('idx_metadata_framework', 'metadata', ['framework'], unique=False)
    op.create_index('idx_metadata_model_type', 'metadata', ['model_type'], unique=False)
    op.create_index('idx_metadata_status', 'metadata', ['status'], unique=False)
    op.create_index('idx_metadata_task_type', 'metadata', ['task_type'], unique=False)
    op.create_index('uk_metadata_model_id', 'metadata', ['model_id'], unique=True)
    op.create_index('uk_metadata_name', 'metadata', ['name'], unique=True)
    op.create_table('requests',
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='请求 ID，请求的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='目标模型 ID'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求负载，JSON 格式'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='请求来源，如 api'),
    sa.Column('latency_ms', sa.Float(), nullable=True, comment='处理耗时，单位毫秒'),
    sa.Column('user', sa.String(length=64), nullable=True, comment='用户标识'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='客户端 IP 地址'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_requests_request_id'))
    )
    op.create_index('idx_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_requests_model_id', 'requests', ['model_id'], unique=False)
    op.create_index('idx_requests_request_id', 'requests', ['request_id'], unique=False)
    op.create_index('idx_requests_source', 'requests', ['source'], unique=False)
    op.create_index('idx_requests_user', 'requests', ['user'], unique=False)
    op.create_table('routing',
    sa.Column('routing_id', sa.String(length=64), nullable=False, comment='路由 ID，路由的唯一标志'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='路由名称'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('strategy', sa.String(length=20), nullable=False, comment='版本选择策略，可选值：random / consistent / bucket / weighted'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='策略配置参数，JSON 格式'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否启用'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing'))
    )
    op.create_index('idx_routing_enabled', 'routing', ['enabled'], unique=False)
    op.create_index('idx_routing_model_id', 'routing', ['model_id'], unique=False)
    op.create_index('idx_routing_routing_id', 'routing', ['routing_id'], unique=True)
    op.create_index('idx_routing_strategy', 'routing', ['strategy'], unique=False)
    op.create_table('versions',
    sa.Column('version_id', sa.String(length=64), nullable=False, comment='版本 ID，模型版本的唯一标识'),
    sa.Column('model_id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('framework', sa.String(length=50), nullable=False, comment='框架类型，如 sklearn / xgboost / lightgbm / catboost / torch / onnx / tensorflow'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False, comment='状态，可选值：active / inactive / deprecated / archived'),
    sa.Column('bento_tag', sa.String(length=100), nullable=False, comment='BentoML 标签，格式为 模型名:版本'),
    sa.Column('model_path', sa.String(length=255), nullable=False, comment='模型文件存储路径'),
    sa.Column('storage_key', sa.String(length=255), nullable=False, comment='存储键，模型文件在存储空间中的唯一标识'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型参数，JSON 格式'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模型评估指标，JSON 格式'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本说明'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除人'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='归档时间'),
    sa.Column('archived_by', sa.String(length=50), nullable=True, comment='归档人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    op.create_index('idx_versions_created_at', 'versions', ['created_at'], unique=False)
    op.create_index('idx_versions_framework', 'versions', ['framework'], unique=False)
    op.create_index('idx_versions_model_id', 'versions', ['model_id'], unique=False)
    op.create_index('idx_versions_status', 'versions', ['status'], unique=False)
    op.create_index('uk_versions_model_id_version', 'versions', ['model_id', 'version'], unique=True)
    op.create_index('uk_versions_version_id', 'versions', ['version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构（downgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_versions_version_id', table_name='versions')
    op.drop_index('uk_versions_model_id_version', table_name='versions')
    op.drop_index('idx_versions_status', table_name='versions')
    op.drop_index('idx_versions_model_id', table_name='versions')
    op.drop_index('idx_versions_framework', table_name='versions')
    op.drop_index('idx_versions_created_at', table_name='versions')
    op.drop_table('versions')
    op.drop_index('idx_routing_strategy', table_name='routing')
    op.drop_index('idx_routing_routing_id', table_name='routing')
    op.drop_index('idx_routing_model_id', table_name='routing')
    op.drop_index('idx_routing_enabled', table_name='routing')
    op.drop_table('routing')
    op.drop_index('idx_requests_user', table_name='requests')
    op.drop_index('idx_requests_source', table_name='requests')
    op.drop_index('idx_requests_request_id', table_name='requests')
    op.drop_index('idx_requests_model_id', table_name='requests')
    op.drop_index('idx_requests_created_at', table_name='requests')
    op.drop_table('requests')
    op.drop_index('uk_metadata_name', table_name='metadata')
    op.drop_index('uk_metadata_model_id', table_name='metadata')
    op.drop_index('idx_metadata_task_type', table_name='metadata')
    op.drop_index('idx_metadata_status', table_name='metadata')
    op.drop_index('idx_metadata_model_type', table_name='metadata')
    op.drop_index('idx_metadata_framework', table_name='metadata')
    op.drop_index('idx_metadata_created_at', table_name='metadata')
    op.drop_table('metadata')
    op.drop_index('uk_experiments_experiment_id', table_name='experiments')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id', table_name='experiments')
    op.drop_index('idx_experiments_effective_time', table_name='experiments')
    op.drop_index('idx_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('uk_deployments_deployment_id', table_name='deployments')
    op.drop_index('idx_deployments_model_version', table_name='deployments')
    op.drop_index('idx_deployments_model_id', table_name='deployments')
    op.drop_index('idx_deployments_framework', table_name='deployments')
    op.drop_index('idx_deployments_environment_variant_status', table_name='deployments')
    op.drop_index('idx_deployments_effective_time', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('uk_audit_audit_id', table_name='audit')
    op.drop_index('idx_audit_user_occurred_at', table_name='audit')
    op.drop_index('idx_audit_trace_id_occurred_at', table_name='audit', postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.drop_index('idx_audit_target_type_occurred_at', table_name='audit')
    op.drop_index('idx_audit_target_id_occurred_at', table_name='audit')
    op.drop_index('idx_audit_source_occurred_at', table_name='audit')
    op.drop_index('idx_audit_request_id_occurred_at', table_name='audit', postgresql_where=sa.text('request_id IS NOT NULL'))
    op.drop_index('idx_audit_occurred_at', table_name='audit')
    op.drop_index('idx_audit_failed_occurred_at', table_name='audit', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('audit')
    op.drop_index('uk_assignments_request_id', table_name='assignments')
    op.drop_index('uk_assignments_assignment_id', table_name='assignments')
    op.drop_index('idx_assignments_version_id', table_name='assignments')
    op.drop_index('idx_assignments_source', table_name='assignments')
    op.drop_index('idx_assignments_model_id', table_name='assignments')
    op.drop_index('idx_assignments_experiment_id', table_name='assignments')
    op.drop_index('idx_assignments_deployment_id', table_name='assignments')
    op.drop_index('idx_assignments_customer_id', table_name='assignments')
    op.drop_index('idx_assignments_created_at', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###