"""init schema

Revision ID: 42f6925ba0c6
Revises: 
Create Date: 2026-04-30 10:53:14.827984+00:00

说明：
本文件由 Alembic 自动生成，请谨慎修改。
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '42f6925ba0c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构（upgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('routed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index('idx_assignments_created_at', 'assignments', ['created_at'], unique=False)
    op.create_index('idx_assignments_model_id', 'assignments', ['model_id'], unique=False)
    op.create_index('idx_assignments_model_version', 'assignments', ['model_id', 'version'], unique=False)
    op.create_index('idx_assignments_request_id', 'assignments', ['request_id'], unique=False)
    op.create_index('idx_assignments_source', 'assignments', ['source'], unique=False)
    op.create_index('idx_assignments_user', 'assignments', ['user'], unique=False)
    op.create_table('audit',
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_index('idx_audit_failed_occurred_at', 'audit', ['occurred_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    op.create_index('idx_audit_occurred_at', 'audit', ['occurred_at'], unique=False)
    op.create_index('idx_audit_target_id_occurred_at', 'audit', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_target_type_occurred_at', 'audit', ['target_type', 'occurred_at'], unique=False)
    op.create_index('idx_audit_trace_id_occurred_at', 'audit', ['trace_id', 'occurred_at'], unique=False, postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.create_index('idx_audit_user_occurred_at', 'audit', ['user', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_request_id'), 'audit', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_trace_id'), 'audit', ['trace_id'], unique=False)
    op.create_table('deployments',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('traffic_ratio', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('deployed_by', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('traffic_ratio >= 0 AND traffic_ratio <= 1', name=op.f('ck_deployments_ck_traffic_ratio_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index('idx_deployments_effective_time', 'deployments', ['model_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_deployments_framework', 'deployments', ['framework'], unique=False)
    op.create_index('idx_deployments_model_id', 'deployments', ['model_id'], unique=False)
    op.create_index('idx_deployments_status', 'deployments', ['status'], unique=False)
    op.create_index('idx_deployments_version', 'deployments', ['model_id', 'version'], unique=False)
    op.create_index('uk_deployments_model_id_version', 'deployments', ['model_id', 'version'], unique=True)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('experiment_id', name=op.f('uq_experiments_experiment_id'))
    )
    op.create_index('idx_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('idx_experiments_effective_time', 'experiments', ['effective_from', 'effective_to'], unique=False)
    op.create_index('idx_experiments_model_id', 'experiments', ['model_id'], unique=False)
    op.create_index('idx_experiments_model_id_status', 'experiments', ['model_id', 'status'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_table('metadata',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata')),
    sa.UniqueConstraint('model_id', name=op.f('uq_metadata_model_id')),
    sa.UniqueConstraint('name', name=op.f('uq_metadata_name'))
    )
    op.create_index('idx_metadata_created_at', 'metadata', ['created_at'], unique=False)
    op.create_index('idx_metadata_framework', 'metadata', ['framework'], unique=False)
    op.create_index('idx_metadata_model_type', 'metadata', ['model_type'], unique=False)
    op.create_index('idx_metadata_name', 'metadata', ['name'], unique=False)
    op.create_index('idx_metadata_status', 'metadata', ['status'], unique=False)
    op.create_index('idx_metadata_task_type', 'metadata', ['task_type'], unique=False)
    op.create_table('requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_requests_request_id'))
    )
    op.create_index('idx_requests_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_requests_model_id', 'requests', ['model_id'], unique=False)
    op.create_index('idx_requests_request_id', 'requests', ['request_id'], unique=False)
    op.create_index('idx_requests_source', 'requests', ['source'], unique=False)
    op.create_index('idx_requests_user', 'requests', ['user'], unique=False)
    op.create_table('routing',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routing'))
    )
    op.create_index('idx_routing_enabled', 'routing', ['enabled'], unique=False)
    op.create_index('idx_routing_model_id', 'routing', ['model_id'], unique=False)
    op.create_index('idx_routing_strategy', 'routing', ['strategy'], unique=False)
    op.create_table('versions',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('bento_tag', sa.String(length=100), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    op.create_index('idx_versions_bento_tag', 'versions', ['bento_tag'], unique=False)
    op.create_index('idx_versions_created_at', 'versions', ['created_at'], unique=False)
    op.create_index('idx_versions_framework', 'versions', ['framework'], unique=False)
    op.create_index('idx_versions_model_id', 'versions', ['model_id'], unique=False)
    op.create_index('uk_versions_model_id_version', 'versions', ['model_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构（downgrade）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uk_versions_model_id_version', table_name='versions')
    op.drop_index('idx_versions_model_id', table_name='versions')
    op.drop_index('idx_versions_framework', table_name='versions')
    op.drop_index('idx_versions_created_at', table_name='versions')
    op.drop_index('idx_versions_bento_tag', table_name='versions')
    op.drop_table('versions')
    op.drop_index('idx_routing_strategy', table_name='routing')
    op.drop_index('idx_routing_model_id', table_name='routing')
    op.drop_index('idx_routing_enabled', table_name='routing')
    op.drop_table('routing')
    op.drop_index('idx_requests_user', table_name='requests')
    op.drop_index('idx_requests_source', table_name='requests')
    op.drop_index('idx_requests_request_id', table_name='requests')
    op.drop_index('idx_requests_model_id', table_name='requests')
    op.drop_index('idx_requests_created_at', table_name='requests')
    op.drop_table('requests')
    op.drop_index('idx_metadata_task_type', table_name='metadata')
    op.drop_index('idx_metadata_status', table_name='metadata')
    op.drop_index('idx_metadata_name', table_name='metadata')
    op.drop_index('idx_metadata_model_type', table_name='metadata')
    op.drop_index('idx_metadata_framework', table_name='metadata')
    op.drop_index('idx_metadata_created_at', table_name='metadata')
    op.drop_table('metadata')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id_status', table_name='experiments')
    op.drop_index('idx_experiments_model_id', table_name='experiments')
    op.drop_index('idx_experiments_effective_time', table_name='experiments')
    op.drop_index('idx_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('uk_deployments_model_id_version', table_name='deployments')
    op.drop_index('idx_deployments_version', table_name='deployments')
    op.drop_index('idx_deployments_status', table_name='deployments')
    op.drop_index('idx_deployments_model_id', table_name='deployments')
    op.drop_index('idx_deployments_framework', table_name='deployments')
    op.drop_index('idx_deployments_effective_time', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_audit_trace_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_request_id'), table_name='audit')
    op.drop_index('idx_audit_user_occurred_at', table_name='audit')
    op.drop_index('idx_audit_trace_id_occurred_at', table_name='audit', postgresql_where=sa.text('trace_id IS NOT NULL'))
    op.drop_index('idx_audit_target_type_occurred_at', table_name='audit')
    op.drop_index('idx_audit_target_id_occurred_at', table_name='audit')
    op.drop_index('idx_audit_occurred_at', table_name='audit')
    op.drop_index('idx_audit_failed_occurred_at', table_name='audit', postgresql_where=sa.text("status = 'failed'"))
    op.drop_table('audit')
    op.drop_index('idx_assignments_user', table_name='assignments')
    op.drop_index('idx_assignments_source', table_name='assignments')
    op.drop_index('idx_assignments_request_id', table_name='assignments')
    op.drop_index('idx_assignments_model_version', table_name='assignments')
    op.drop_index('idx_assignments_model_id', table_name='assignments')
    op.drop_index('idx_assignments_created_at', table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###