databases:
  oracle:
    host: "localhost"             # 主机
    port: 1521                    # 端口
    service_name: "FREEPDB1"
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600

  postgres:
    host: "localhost"             # 主机
    port: 5432                    # 端口
    database: "bankgy"            # 数据库名
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600

logging:
  name: "DatamindLogger"
  level: "INFO"
  file: "logs/Datamind.log"
  max_bytes: 10485760
  backup_count: 5
  use_concurrent: true

kie_server:
  url: http://localhost:8080/kie-server/services/rest/server
  username: admin
  password: admin

features:
  demo_loan_features:
  - age
  - income
  - debt_ratio
  - loan_amount
  - existing_loans
  - total_tax_records
  - total_tax_amount
  - avg_tax_amount
  - max_tax_amount
  - min_tax_amount
  - tax_amount_std
  - loan_to_income_ratio
  - existing_loans_ratio

models:
  scoring:
  - model_name: demo_loan_scorecard_lr_20250930
    model_type: logistic_regression
    model_path: "models/demo_loan_scorecard_lr_20250930.pkl"
    version: ""
    uuid: ""
    framework: sklearn
    features: demo_loan_features

  - model_name: demo_loan_scorecard_dt_20250930
    model_type: decision_tree
    model_path: "models/demo_loan_scorecard_dt_20250930.pkl"
    version: ""
    uuid: ""
    framework: sklearn
    features: demo_loan_features

  - model_name: demo_loan_scorecard_rf_20250930
    model_type: random_forest
    model_path: "models/demo_loan_scorecard_rf_20250930.pkl"
    version: ""
    uuid: ""
    framework: sklearn
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_lgbm_20250930"
    model_type: "lightgbm"
    model_path: "models/demo_loan_scorecard_lgbm_20250930.pkl"
    version: ""
    uuid: ""
    framework: "lightgbm"
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_xgb_20250930"
    model_type: "xgboost"
    model_path: "models/demo_loan_scorecard_xgb_20250930.pkl"
    version: ""
    uuid: ""
    framework: "xgboost"
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_cat_20250930"
    model_type: "catboost"
    model_path: "models/demo_loan_scorecard_cat_20250930.cbm"
    version: ""
    uuid: ""
    framework: "catboost"
    features: demo_loan_features

  fraud:
  - model_name: "demo_loan_fraud_detection_cat_20250930"
    model_type: "catboost"
    model_path: "models/demo_loan_fraud_detection_cat_20250930.cbm"
    version: ""
    uuid: ""
    framework: "catboost"
    features: demo_loan_features

workflows:
  demo_loan_approval_workflow:
    business_name: demo_loan
    description: "零售信贷业务授信审批流程"
    models:
    - model_name: demo_loan_scorecard_lr
      ab_test:
        group: "A"
        weight: 0.6
        environment: "prod"   #dev/staging/prod
    - model_name: demo_loan_scorecard_dt
      ab_test:
        group: "B"
        weight: 0.4
        environment: "prod"
    - model_name: demo_loan_fraud_detection_cat
      ab_test: {}
    workflow_steps:
    - step_name: "rule_check"
      contain_name: kie_container_name
      modules:
      - name: "Basic Eligibility"
        description: "基本准入要求"
        enabled: true
        rules:
        - name: "Age Not Eligible"
          description: "年龄需满足18岁以上，65岁以下"
          hint: "年龄不符合要求"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Age + Credit Term Exceeds Limit"
          description: "年龄+授信期限不超过65岁数"
          hint: "年龄+授信期限不符合要求"
          agenda_group: "basic_eligibility"
          enabled: false
        - name: "Suspected Illegal Activity"
          description: "借款人涉嫌黄赌毒"
          hint: "借款人涉嫌黄赌毒"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Not In Whitelist"
          description: "申请人不在白名单"
          hint: "申请人不在白名单"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Not a Farmer"
          description: "借款人不是农户"
          hint: "借款人不是农户"
          agenda_group: "basic_eligibility"
          enabled: true
      - name: "Policy Check"
        description: "产品政策检查"
        enabled: true
        rules:
        - name: "Business Duration"
          description: "经营期限过短"
          hint: "正常经营期限<6个月"
          agenda_group: "policy_check"
          enabled: true
        - name: "Crop Duration"
          description: "种植期限过短"
          hint: "种植烟草期限不足1年"
          agenda_group: "policy_check"
          enabled: false
        - name: "Purpose Consistency"
          description: "借款人申请用途与实际用途不一致"
          hint: "借款人申请用途与实际用途不一致"
          agenda_group: "policy_check"
          enabled: true
      - name: "Credit Check"
        description: "征信要求"
        enabled: true
        rules:
        - name: "last_3m_self_queries"
          description: "近三个月本人查询次数"
          hint: "近三个月本人查询次数超出范围"
          agenda_group: "basic_qualification"
          enabled: true
        - name: "last_3m_agency_queries"
          description: "近三个月机构查询次数"
          hint: "近三个月机构查询次数超出范围"
          agenda_group: "basic_qualification"
          enabled: false
      - name: "Internal Check"
        description: "内部信息检查"
        enabled: false
        rules:
        - name: "Current Overdue"
          description: "当前有逾期"
          hint: "当前有逾期"
          agenda_group: "internal_check"
          enabled: true
        - name: "Past 24-Month Loan Overdue"
          description: "近24个月历史贷款有逾期"
          hint: "近24个月历史贷款有逾期"
          agenda_group: "internal_check"
          enabled: true
    - step_name: "fraud_check"
      models: ["demo_loan_fraud_detection_cat"]
    - step_name: "model_scoring"
      models: ["demo_loan_scorecard_lr", "demo_loan_scorecard_dt"]

  demo_loan_disbursement_workflow:
    business_name: demo_loan
    description: "零售信贷业务贷款支用流程"
    models:
    - model_name: demo_loan_scorecard_lr
      ab_test:
        group: "A"
        weight: 0.6
        environment: "prod"   #dev/staging/prod
    - model_name: demo_loan_scorecard_dt
      ab_test:
        group: "B"
        weight: 0.4
        environment: "prod"
    - model_name: demo_loan_fraud_detection_cat
      ab_test: {}
    workflow_steps:
    - step_name: "rule_check"
      contain_name: kie_container_name
      modules:
      - name: "Policy Check"
        description: "政策信息检查"
        enabled: true
        rules:
        - name: "Whitelist Check"
          description: "白名单检查"
          hint: "借款人不属于白名单内客户"
          agenda_group: "policy_check"
          enabled: true
      - name: "Business Check"
        description: "产品政策检查"
        enabled: true
        rules:
        - name: "Registration Status"
          description: "工商登记状态异常"
          hint: "工商登记状态异常"
          agenda_group: "business_check"
          enabled: true
        - name: "License Expiry"
          description: "营业执照过期"
          hint: "营业执照过期"
          agenda_group: "business_check"
          enabled: true
      - name: "Internal Check"
        description: "内部信息检查"
        enabled: false
        rules:
        - name: "Current Overdue"
          description: "当前有逾期"
          hint: "当前有逾期"
          agenda_group: "internal_check"
          enabled: true
        - name: "Past 24-Month Loan Overdue"
          description: "近24个月历史贷款有逾期且申请时点至支用时点新增的逾期"
          hint: "行内还款记录显示，近12个月内最高逾期＞=3，（还款方式为不规则还款时，最高逾期＞=2）"
          agenda_group: "internal_check"
          enabled: true
    - step_name: "fraud_check"
      models: ["demo_loan_fraud_detection_cat"]
