databases:
  oracle:
    host: "192.168.15.129"        # 主机
    port: 1521                    # 端口
    service_name: "FREEPDB1"
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600  

  postgres:
    host: "192.168.15.129"        # 主机
    port: 5432                    # 端口
    database: "bankgy"            # 数据库名
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600

logging:
  name: "DatamindLogger"
  level: "INFO"
  file: "logs/Datamind.log"
  max_bytes: 10485760
  backup_count: 5
  use_concurrent: true

model_registry:
  scoring:
    model_name: "demo_loan_scorecard_lr_20250930"
    model_type: "logistic_regression"
    model_path: "models/demo_loan_scorecard_lr_20250930.pkl"
    version: ""
    uuid: ""
    framework: "sklearn"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]
    rule:
       rule_path: "rules/demo_loan_rules_20250930.yaml"
       enabled_categories: ["pre_check", "blacklist", "credit", "third_party"]
       enabled_groups: ["basic_qualification", "internal_blacklist", "credit_score", "tax"]
       enabled_rule_ids: ["R001","R002","R010","R020","R030"]

  demo_loan_dt:
    model_name: "demo_loan_scorecard_dt_20250930"
    model_type: "decision_tree"
    model_path: "models/demo_loan_scorecard_dt_20250930.pkl"
    version: ""
    uuid: ""
    framework: "sklearn"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]

  demo_loan_rf:
    model_name: "demo_loan_scorecard_rf_20250930"
    model_type: "random_forest"
    model_path: "models/demo_loan_scorecard_rf_20250930.pkl"
    version: ""
    uuid: ""
    framework: "sklearn"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]

  demo_loan_lightgbm:
    model_name: "demo_loan_scorecard_lgbm_20250930"
    model_type: "lightgbm"
    model_path: "models/demo_loan_scorecard_lgbm_20250930.pkl"
    version: ""
    uuid: ""
    framework: "lightgbm"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]

  demo_loan_xgboost:
    model_name: "demo_loan_scorecard_xgb_20250930"
    model_type: "xgboost"
    model_path: "models/demo_loan_scorecard_xgb_20250930.pkl"
    version: ""
    uuid: ""
    framework: "xgboost"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]

  demo_loan_catboost:
    model_name: "demo_loan_scorecard_cat_20250930"
    model_type: "catboost"
    model_path: "models/demo_loan_fraud_detection_cat_20250930.cbm"
    version: ""
    uuid: ""
    framework: "catboost"
    features: [ "age", "income", "debt_ratio", "loan_amount", "existing_loans", "total_tax_records",
                "total_tax_amount", "avg_tax_amount","max_tax_amount", "min_tax_amount" , "tax_amount_std",
                "loan_to_income_ratio", "existing_loans_ratio" ]