databases:
  oracle:
    host: "localhost"        # 主机
    port: 1521                    # 端口
    service_name: "FREEPDB1"
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600  

  postgres:
    host: "localhost"        # 主机
    port: 5432                    # 端口
    database: "bankgy"            # 数据库名
    user: "bankgy"                # 用户名
    password: "bankgy"            # 密码
    pool_size: 5                  # 连接池最小连接数
    max_overflow: 10              # 连接池最大溢出连接数
    pool_timeout: 60
    pool_recycle: 3600

logging:
  name: "DatamindLogger"
  level: "INFO"
  file: "logs/Datamind.log"
  max_bytes: 10485760
  backup_count: 5
  use_concurrent: true

kie_server:
  url: http://localhost:8080/kie-server/services/rest/server
  username: admin
  password: admin

feature_set:
  demo_loan_features:
    - age
    - income
    - debt_ratio
    - loan_amount
    - existing_loans
    - total_tax_records
    - total_tax_amount
    - avg_tax_amount
    - max_tax_amount
    - min_tax_amount
    - tax_amount_std
    - loan_to_income_ratio
    - existing_loans_ratio

model_catalog:
  scoring:
    - model_name: demo_loan_scorecard_lr_20250930
      model_type: logistic_regression
      model_path: "models/demo_loan_scorecard_lr_20250930.pkl"
      version: ""
      uuid: ""
      framework: sklearn
      features: demo_loan_features

    - model_name: demo_loan_scorecard_dt_20250930
      model_type: decision_tree
      model_path: "models/demo_loan_scorecard_dt_20250930.pkl"
      version: ""
      uuid: ""
      framework: sklearn
      features: demo_loan_features


    - model_name: demo_loan_scorecard_rf_20250930
      model_type: random_forest
      model_path: "models/demo_loan_scorecard_rf_20250930.pkl"
      version: ""
      uuid: ""
      framework: sklearn
      features: demo_loan_features

    - model_name: "demo_loan_scorecard_lgbm_20250930"
      model_type: "lightgbm"
      model_path: "models/demo_loan_scorecard_lgbm_20250930.pkl"
      version: ""
      uuid: ""
      framework: "lightgbm"
      features: demo_loan_features

    - model_name: "demo_loan_scorecard_xgb_20250930"
      model_type: "xgboost"
      model_path: "models/demo_loan_scorecard_xgb_20250930.pkl"
      version: ""
      uuid: ""
      framework: "xgboost"
      features: demo_loan_features

    - model_name: "demo_loan_scorecard_cat_20250930"
      model_type: "catboost"
      model_path: "models/demo_loan_scorecard_cat_20250930.cbm"
      version: ""
      uuid: ""
      framework: "catboost"
      features: demo_loan_features

  fraud:
    - model_name: "demo_loan_fraud_detection_cat_20250930"
      model_type: "catboost"
      model_path: "models/demo_loan_fraud_detection_cat_20250930.cbm"
      version: ""
      uuid: ""
      framework: "catboost"
      features: demo_loan_features

business_workflows:
  demo_loan_approval_workflow:
    business_name: demo_loan
    description: "零售信贷业务授信审批流程"
    models:
      - model_name: demo_loan_scorecard_lr
        ab_test:
          group: "A"
          weight: 0.6
          environment: "prod" #dev/staging/prod
      - model_name: demo_loan_scorecard_dt
        ab_test:
          group: "B"
          weight: 0.4
          environment: "prod"
      - model_name: demo_loan_fraud_detection_cat
        ab_test: { }
    workflow_steps:
      - step_name: "rule_check"
        contain_name: kie_container_name
        agenda_group: "credit"
        modules:
          - name: "precheck"
            enabled: true
            rules:
              - name: "precheck_amount_rule"
                enabled: true
              - name: "precheck_age_rule"
                enabled: true
          - name: "credit_check"
            enabled: true
            rules:
              - name: "credit_score_rule"
                enabled: true
              - name: "credit_history_rule"
                enabled: false
          - name: "tax_check"
            enabled: false
            rules:
              - name: "tax_income_rule"
                enabled: false
      - step_name: "fraud_check"
        models: [ "demo_loan_fraud_detection_cat" ]
      - step_name: "model_scoring"
        models: [ "demo_loan_scorecard_lr", "demo_loan_scorecard_dt" ]

  demo_loan_disbursement_workflow:
    business_name: demo_loan
    description: "零售信贷业务贷款支用流程"
    models:
      - model_name: demo_loan_scorecard_lr
        ab_test:
          group: "A"
          weight: 0.6
          environment: "prod" #dev/staging/prod
      - model_name: demo_loan_scorecard_dt
        ab_test:
          group: "B"
          weight: 0.4
          environment: "prod"
      - model_name: demo_loan_fraud_detection_cat
        ab_test: { }
    workflow_steps:
      - step_name: "rule_check"
        contain_name: kie_container_name
        modules:
          - name: "basic_qualification"
            enabled: true
            rules:
              - name: "age_requirement"
                description: "年龄需满足18岁以上，65岁以下"
                hint: "年龄不符合要求"
                agenda_group: "credit"
                enabled: true
              - name: "precheck_age_rule"
                enabled: true
          - name: "credit_check"
            enabled: true
            rules:
              - name: "credit_score_rule"
                enabled: true
              - name: "credit_history_rule"
                enabled: false
          - name: "tax_check"
            enabled: false
            rules:
              - name: "tax_income_rule"
                enabled: false
      - step_name: "fraud_check"
        models: [ "demo_loan_fraud_detection_cat" ]
      - step_name: "model_scoring"
        models: [ "demo_loan_scorecard_lr", "demo_loan_scorecard_dt" ]
