databases:
  oracle:
    host: "${ORACLE_HOST:-localhost}"                    # 主机（默认 localhost）
    port: ${ORACLE_PORT:-1521}                           # 端口
    service_name: "${ORACLE_SERVICE_NAME:-FREEPDB1}"
    user: "${ORACLE_APP_USER:-datamind}"                   # 用户名
    password: "${ORACLE_APP_USER_PASSWORD:-datamind}"      # 密码
    pool_size: ${ORACLE_POOL_SIZE:-5}                    # 连接池最小连接数
    max_overflow: ${ORACLE_MAX_OVERFLOW:-10}             # 连接池最大溢出连接数
    pool_timeout: ${ORACLE_POOL_TIMEOUT:-60}
    pool_recycle: ${ORACLE_POOL_RECYCLE:-3600}

  postgres:
    host: "${POSTGRES_HOST:-localhost}"                  # 主机
    port: ${POSTGRES_PORT:-5432}                         # 端口
    database: "${POSTGRES_DB:-datamind}"                 # 数据库名
    user: "${POSTGRES_USER:-datamind}"                   # 用户名
    password: "${POSTGRES_PASSWORD:-datamind}"           # 密码
    pool_size: ${POSTGRES_POOL_SIZE:-5}
    max_overflow: ${POSTGRES_MAX_OVERFLOW:-10}
    pool_timeout: ${POSTGRES_POOL_TIMEOUT:-60}
    pool_recycle: ${POSTGRES_POOL_RECYCLE:-3600}

logging:
  name: "${DATAMIND_LOG_NAME:-DatamindLogger}"
  level: "${DATAMIND_LOG_LEVEL:-INFO}"
  file: "${DATAMIND_LOG_FILE:-logs/Datamind.log}"
  max_bytes: ${DATAMIND_LOG_MAX_BYTES:-10485760}
  backup_count: ${DATAMIND_LOG_BACKUP_COUNT:-5}
  use_concurrent: ${DATAMIND_LOG_USE_CONCURRENT:-true}

kie_server:
  url: "${KIE_SERVER_URL:-http://localhost:8080/kie-server/services/rest/server}"
  username: "${KIE_SERVER_USER:-admin}"
  password: "${KIE_SERVER_PASSWORD:-admin}"

features:
  demo_loan_features:
  - age
  - income
  - debt_ratio
  - loan_amount
  - existing_loans
  - total_tax_records
  - total_tax_amount
  - avg_tax_amount
  - max_tax_amount
  - min_tax_amount
  - tax_amount_std
  - loan_to_income_ratio
  - existing_loans_ratio

models:
  scoring:
  - model_name: demo_loan_scorecard_lr_20250930
    model_type: logistic_regression
    model_path: "models/demo_loan_scorecard_lr_20250930.pkl"
    version: "2vunfhf33o5tvglm"
    uuid: "9b95a32d-a6ef-525e-afd4-027ba96e6f31"
    hash: "10e80124a0bd9d1a873cf1f47b1761ee368b1d0d34a89a580d3fb6708138bbf7"
    framework: sklearn
    features: demo_loan_features

  - model_name: demo_loan_scorecard_dt_20250930
    model_type: decision_tree
    model_path: "models/demo_loan_scorecard_dt_20250930.joblib"
    version: "2vunfhv33o5tvglm"
    uuid: "6bfc355c-2677-5f02-9f03-3919d1f3f19d"
    hash: "f10f11844d377d22d85b9eaddf06842cf72bcbdbf6bb239b8bf5650645f869a9"
    framework: sklearn
    features: demo_loan_features

  - model_name: demo_loan_scorecard_rf_20250930
    model_type: random_forest
    model_path: "models/demo_loan_scorecard_rf_20250930.joblib"
    version: "22r7lcf33o5tvglm"
    uuid: "76e1e4c5-33a6-5de5-aa70-fa3cfea5a354"
    hash: "b92254a69f225dbad55f7fe2ab3f0260860c8d9fd4867b44ba49af4fbf49e95a"
    framework: sklearn
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_lgbm_20250930"
    model_type: "lightgbm"
    model_path: "models/demo_loan_scorecard_lgbm_20250930.lgb"
    version: "22r7lcn33o5tvglm"
    uuid: "0da70fcd-39cd-50c1-bc39-445dd178ae1e"
    hash: "13732de57383c92b6c0b7d1e9cca77db9dfb5b43c9e48b41b6d7b31fbd094bcf"
    framework: "lightgbm"
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_xgb_20250930"
    model_type: "xgboost"
    model_path: "models/demo_loan_scorecard_xgb_20250930.json"
    version: "27j6krf33o5tvglm"
    uuid: "e9d70321-2c13-5efe-93c5-076ec13050b9"
    hash: "59630d5e530e2b8432279f8b3621bb0cdb405fb91cfd4f0454c03b4603c436ab"
    framework: "xgboost"
    features: demo_loan_features

  - model_name: "demo_loan_scorecard_cat_20250930"
    model_type: "catboost"
    model_path: "models/demo_loan_scorecard_cat_20250930.cbm"
    version: "27j6krn33o5tvglm"
    uuid: "dc6953b0-0907-525c-b2a4-94373ae4d1e1"
    hash: "2eab00a9bd5c6578025e7e457ecff4278e5f99b968e298833971173b9d08f422"
    framework: "catboost"
    features: demo_loan_features

  fraud:
  - model_name: "demo_loan_fraud_detection_cat_20250930"
    model_type: "catboost"
    model_path: "models/demo_loan_fraud_detection_cat_20250930.cbm"
    version: "27j6krv33o5tvglm"
    uuid: "75fb017f-81a1-512e-a3fc-3a589983a579"
    hash: "3216c6b870e683724e4ba05cc503d53f1251c78fc32f1c7f72bdb2e0931da4bb"
    framework: "catboost"
    features: demo_loan_features

workflows:
  demo_loan_approval_workflow:
    business_name: demo_loan
    description: "零售信贷业务授信审批流程"
    models:
    - model_name: demo_loan_scorecard_lr_20250930
      ab_test:
        group: "A"
        weight: 0.6
        environment: "prod"   #dev/staging/prod
    - model_name: demo_loan_scorecard_dt_20250930
      ab_test:
        group: "B"
        weight: 0.4
        environment: "prod"
    - model_name: demo_loan_fraud_detection_cat_20250930
      ab_test: {}
    workflow_steps:
    - step_name: "rule_check"
      description: "规则检查"
      enabled: false
      contain_name: kie_container_name
      modules:
      - name: "Basic Eligibility"
        description: "基本准入要求"
        enabled: true
        rules:
        - name: "Age Not Eligible"
          description: "年龄需满足18岁以上，65岁以下"
          hint: "年龄不符合要求"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Age + Credit Term Exceeds Limit"
          description: "年龄+授信期限不超过65岁数"
          hint: "年龄+授信期限不符合要求"
          agenda_group: "basic_eligibility"
          enabled: false
        - name: "Suspected Illegal Activity"
          description: "借款人涉嫌黄赌毒"
          hint: "借款人涉嫌黄赌毒"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Not In Whitelist"
          description: "申请人不在白名单"
          hint: "申请人不在白名单"
          agenda_group: "basic_eligibility"
          enabled: true
        - name: "Not a Farmer"
          description: "借款人不是农户"
          hint: "借款人不是农户"
          agenda_group: "basic_eligibility"
          enabled: true
      - name: "Policy Check"
        description: "产品政策检查"
        enabled: true
        rules:
        - name: "Business Duration"
          description: "经营期限过短"
          hint: "正常经营期限<6个月"
          agenda_group: "policy_check"
          enabled: true
        - name: "Crop Duration"
          description: "种植期限过短"
          hint: "种植烟草期限不足1年"
          agenda_group: "policy_check"
          enabled: false
        - name: "Purpose Consistency"
          description: "借款人申请用途与实际用途不一致"
          hint: "借款人申请用途与实际用途不一致"
          agenda_group: "policy_check"
          enabled: true
      - name: "Credit Check"
        description: "征信要求"
        enabled: true
        rules:
        - name: "last_3m_self_queries"
          description: "近三个月本人查询次数"
          hint: "近三个月本人查询次数超出范围"
          agenda_group: "basic_qualification"
          enabled: true
        - name: "last_3m_agency_queries"
          description: "近三个月机构查询次数"
          hint: "近三个月机构查询次数超出范围"
          agenda_group: "basic_qualification"
          enabled: false
      - name: "Internal Check"
        description: "内部信息检查"
        enabled: false
        rules:
        - name: "Current Overdue"
          description: "当前有逾期"
          hint: "当前有逾期"
          agenda_group: "internal_check"
          enabled: true
        - name: "Past 24-Month Loan Overdue"
          description: "近24个月历史贷款有逾期"
          hint: "近24个月历史贷款有逾期"
          agenda_group: "internal_check"
          enabled: true
    - step_name: "fraud_check"
      description: "欺诈检查"
      enabled: false
      models: ["demo_loan_fraud_detection_cat_20250930"]
    - step_name: "model_scoring"
      description: "模型评分"
      enabled: true
      models: ["demo_loan_scorecard_lr_20250930", "demo_loan_scorecard_dt_20250930"]

  demo_loan_disbursement_workflow:
    business_name: demo_loan
    description: "零售信贷业务贷款支用流程"
    models:
    - model_name: demo_loan_scorecard_lr_20250930
      ab_test:
        group: "A"
        weight: 0.6
        environment: "prod"   #dev/staging/prod
    - model_name: demo_loan_scorecard_dt_20250930
      ab_test:
        group: "B"
        weight: 0.4
        environment: "prod"
    - model_name: demo_loan_fraud_detection_cat_20250930
      ab_test: {}
    workflow_steps:
    - step_name: "rule_check"
      contain_name: kie_container_name
      modules:
      - name: "Policy Check"
        description: "政策信息检查"
        enabled: true
        rules:
        - name: "Whitelist Check"
          description: "白名单检查"
          hint: "借款人不属于白名单内客户"
          agenda_group: "policy_check"
          enabled: true
      - name: "Business Check"
        description: "产品政策检查"
        enabled: true
        rules:
        - name: "Registration Status"
          description: "工商登记状态异常"
          hint: "工商登记状态异常"
          agenda_group: "business_check"
          enabled: true
        - name: "License Expiry"
          description: "营业执照过期"
          hint: "营业执照过期"
          agenda_group: "business_check"
          enabled: true
      - name: "Internal Check"
        description: "内部信息检查"
        enabled: false
        rules:
        - name: "Current Overdue"
          description: "当前有逾期"
          hint: "当前有逾期"
          agenda_group: "internal_check"
          enabled: true
        - name: "Past 24-Month Loan Overdue"
          description: "近24个月历史贷款有逾期且申请时点至支用时点新增的逾期"
          hint: "行内还款记录显示，近12个月内最高逾期＞=3，（还款方式为不规则还款时，最高逾期＞=2）"
          agenda_group: "internal_check"
          enabled: true
    - step_name: "fraud_check"
      models: ["demo_loan_fraud_detection_cat"]
